### ISSUE TITLE
Custom Twitter Feed Not Showing Up

### ISSUE THREAD

**Issue by glennmoorecle** [jasonmayes/Twitter-Post-Fetcher#100]
Hey there, my website - www.theglennmoore.com - has Twitter Fetch supposedly on the bottom of the front over of site. 

I have updated the file in my FTP and put in my correct Twitter Widget ID. But still am getting nothing. I also have used a buddy's website that uses the same coding and theme  - his works - and still, nothing.

Just thought I would ask for help on here.

Thanks for what you do.

**Comment by nmacd85** [comment]
you have no domId in your config, and you're getting an error at the line "var latest_tweets = $('#twitter-list');"

Make sure jQuery is loading before your config. You should check that the dom is loaded before anything anyway... so update to something like...

$( document ).ready(function() {
  var latest_tweets = $('#twitter-list');
if(latest_tweets.length) {
	var config = {
	  "id": $('html').attr("data-twitterId"),
	  "domId": 'twitter-list',
	  "maxTweets": 1,
	  "enableLinks": true,
	  "showUser": false,
	  "showTime": true,
	  "dateFunction": '',
	  "showRetweet": false,
	  "customCallback": handleTweets,
	  "showInteraction": false
	};
	function handleTweets(tweets){
	  var x = tweets.length;
	  var n = 0;
	  var html = '<ul>';
	  while(n < x) {
		html += '<li>' + tweets[n] + '</li>';
		n++;
	  }
	  html += '</ul>';
	  latest_tweets.html(html);
	}
	twitterFetcher.fetch(config);
}
});

**Comment by glennmoorecle** [comment]
I apologize for the newbie questions…

So all I need to do is copy and paste what you wrote into the twitterFetcher_v10_min.js after instructions? I did that and it did not update. 

I apologize again.

**Comment by nmacd85** [comment]
Sorry Glenn, looks like some formatting got in there. Try the below, or see the example I made [here](https://codepen.io/nmacd85/pen/wWbBRL) and copy the code from the JS section. 

`$(document).ready(function() {
  var latest_tweets = $('#twitter-list');
  if (latest_tweets.length) {
    var config = {
      "id": $('html').attr("data-twitterId"),
      "domId": '',
      "maxTweets": 1,
      "enableLinks": true,
      "showUser": false,
      "showTime": true,
      "dateFunction": '',
      "showRetweet": false,
      "customCallback": handleTweets,
      "showInteraction": false
    };

    function handleTweets(tweets) {
      var x = tweets.length;
      var n = 0;
      var element = document.getElementById('twitter-list');
      var html = '';
      while (n < x) {
        html += tweets[n];
        n++;
      }
      html += '';
      element.innerHTML = html;
    }

    twitterFetcher.fetch(config);
  }
});`

**Comment by glennmoorecle** [comment]
Hey Nicole. Copied it from the JS section directly and pasted it. Still nothing shows. Even did a hard reset of Chrome and re-inputed my Twitter Widget ID number.

**Comment by nmacd85** [comment]
Next thought would be to take it out of the library js file and have it in its own, load jquery, Twitter fetcher, then your script. 

Or you can look into implementing without the widget id. 

Essentially, the error thrown says it doesn't know what $ is which jquery uses. I would try my First suggestion as you can see in the link I sent before, your config works fine but if jquery isn't loaded first it won't work at all.

**Comment by glennmoorecle** [comment]
I appreciate the responses, and pardon my newbie status, but I'm not familiar with what you're explaining.

Basically, I want it to be like this: http://www.jamesclark.com/

I would love to have it implemented into the site on it's own code and not having to rely the widget ID via the theme's configs.

I'm just not confident enough to do what you have asked without screwing up the site.

**Comment by nmacd85** [comment]
So, I tested a few things and noticed you're using an older version of jQuery, and jQuery migrate to bump up a version but again still an old version. 

You could use this `<script src="https://code.jquery.com/jquery-1.4.1.min.js"></script>` instead of the old version of jQuery and migrate... note, if something on your site DOES require that version. Updating may break the site. If you cant get this to be updated, I would suggest getting someone locally to help you out. It definitely seems like its your jQuery version causing these issues especially since Twitter-Post-Fetcher doesn't require it to run.

Side note: jQuery is a dependancy for other scripts you're using :)

**Comment by glennmoorecle** [comment]
Works! I updated the jQuery via a plugin — it did crash my site, but figured out what other plugin needed it and turns out I don’t need that to be working for my site — updated the Twitter Fetcher script back to the original update and it worked!

Hopefully it works on your end.

Thanks again for the help! You rock!

**Comment by nmacd85** [comment]
Thats great to hear! Glad it worked out :)

**Comment by jasonmayes** [comment]
Thanks to everyone in helping answer question :-) Have been off the radar the last month or so!
