### ISSUE TITLE
Problem using v16.01

### ISSUE THREAD

**Issue by Rwthwyn** [jasonmayes/Twitter-Post-Fetcher#101]
Hi there,

Thanks, Jason, for continuing to develop this great piece of js. I've lost count of the number of sites I've used it on. However, on the latest project I am trying to import it to, I have run into a problem. It's probably user error - these things usually are - but I am getting the following error when using Twitter-Post-Fetcher with Wordpress 4.6:

`Uncaught TypeError: Cannot set property 'innerHTML' of null`

The site I'm using this on is [http://sypotest8.co.uk](http://sypotest8.co.uk)

Any help that anyone can provide would be most useful.

With kind regards,

Mark

**Comment by jasonmayes** [comment]
Sorry for the delay been super busy my end. This seems like the DOM element does not exist before you call Twitter Fetcher.

**Comment by Rwthwyn** [comment]
Hi Jason,

Thanks for coming back to me.

I'm sorry that you felt you had to reply, and it was very kind of you. I wanted to delete this thread - as I'd found that the problem'd been caused by user error and I'd miss-named the DOM element - but didn't know how.

Anyway, thanks again, and I continue to use your excellent, lightweight script.

With kind regards,

Mark
