### ISSUE TITLE
Cannot read property 'replace' of undefined"

### ISSUE THREAD

**Issue by b3smith13** [jasonmayes/Twitter-Post-Fetcher#103]
This is my first time integrating your fantastic plugin via the new methods (without ids). I'm getting "Uncaught TypeError: Cannot read property 'replace' of undefined" which points at this line in my inspector: 

a.body = a.body.replace(/(<img[^c]*class="Emoji[^>]*>)|(<img[^c]*class="u-block[^>]*>)/g, ""),

Any idea what may be the cause here?

**Comment by nmacd85** [comment]
What config are you using, and do you have a live site to view this on or could you mock up a codepen?

**Comment by nmacd85** [comment]
The line you copied seems modified... in the non-min js its 

`// Remove emoji and summary card images.
      data.body = data.body.replace(/(<img[^c]*class="Emoji[^>]*>)|(<img[^c]*class="u-block[^>]*>)/g, '');`

Check if your code has that, maybe re-download the js?

**Comment by b3smith13** [comment]
I think this error was only spitting out because I was having trouble using the new profile option for config and posts were showing before. Was weird but I have it working now, thanks for trying to help!
