### ISSUE TITLE
Replacing 'Posted on' with other text

### ISSUE THREAD

**Issue by Rwthwyn** [jasonmayes/Twitter-Post-Fetcher#105]
Hi there,

This is less of an issue, more of a, 'How do I do that?' question.

I am wondering if anyone with more knowledge of this kind of thing can help. Within the timePosted text, there automatically appears the words, 'Posted on.' I am looking for a way to replace this text with a hyphen, as that is what the design I am working on specifies.

So far I have tried doing it with jQuery, thusly:

    $(document).ready(function(){
        $(".timePosted").text(function () {
            return $(this).text().replace("Posted on", " -"); 
        });
    });

This works once and then doesn't work again.

Any help that you could provide would be most appreciated.

With kind regards,

Mark

**Comment by skeet** [comment]
Hey @Rwthwyn,

You'll be able to do this via the dateFunction parameter which is set when you set up your twitterFetcher. E.g:

```
var configProfile = {
    "profile": {
      "screenName": "github"
    },
    "domId": "tweets",
    "maxTweets": 3,
    "enableLinks": true,
    "linksInNewWindow": true,
    "showUser": false,
    "showTime": true,
    "showImages": false,
    "dateFunction": momentDateFormatter,
    "lang": "en"
  };

twitterFetcher.fetch(configProfile);

}

function momentDateFormatter(date, dateString) {
  return ' -' + moment(dateString).fromNow();
}
```

I've formatted the dateString using Moment, so you'll need to include that too if that's what you want.

**Comment by Rwthwyn** [comment]
Hi @skeet 

Thanks very much for coming back with your answer.

I don't know if you've tested your code, but I've applied it to the site I'm working on and it's unfortunately stopped the Twitter-Post-Fetcher working entirely. Now, this could be down to the code being used on Wordpress and there may be something in that that's stopped it working...

Would you mind having another look?

With kind regards,

Mark

**Comment by skeet** [comment]
That's strange - yeah, I tested my code and it works:

![screen shot 2016-09-07 at 11 23 53](https://cloud.githubusercontent.com/assets/1735459/18308735/b9dcface-74ed-11e6-83c1-1a7e37584936.png)

This is on a static site rather than a Wordpress blog so there might be specific issues there.

Is `domId` set to the container you're loading your tweets into?

Can you confirm what version of Twitter-Post-Fetcher you're using? I'm on the latest version (16.0.2).

Does the profile example work for you? https://github.com/jasonmayes/Twitter-Post-Fetcher/blob/master/js/exampleUsage.js#L88

Cheers,
Keith

**Comment by Rwthwyn** [comment]
Hi @skeet,

Thanks for coming back to me so quickly. As is usual with these things, it was down to user error on my part. I had missed the importance of using Moment.

So, after finding that it worked fine on yours, I re-read your first comment, and then downloaded, installed and referenced `moment.js` and, it works! Thusly:

![untitled](https://cloud.githubusercontent.com/assets/9024589/18309434/4ff54e00-74f1-11e6-8c9d-4dd3a5ea7153.png)

Thanks very much for your help. It was most kind of you.

With kind regards,

Mark

**Comment by skeet** [comment]
Excellent!

No problem, glad you got it working.
