### ISSUE TITLE
Way to exclude tweets that don't have text (i.e. image tweets)?

### ISSUE THREAD

**Issue by samjdavis13** [jasonmayes/Twitter-Post-Fetcher#108]
See title - would like a way to specify to only get tweets that have text content. Is there any plans for something like this?

Thanks!

**Comment by jasonmayes** [comment]
You can simply check if there is text and add to DOM if it matches your criteria. However there is no way using the implemented method to get more than the first 25 tweets no matter if they have text or not as this is all the CDN returns.
