### ISSUE TITLE
add to `cdnjs`

### ISSUE THREAD

**Issue by maruilian11** [jasonmayes/Twitter-Post-Fetcher#111]
hi, recently we want to add your lib to https://cdnjs.com.
I notice that there is v15.0.2 on npm package but not on git repo.
And it seems that not every version is pushed to npm package.
because we usually use **git auto-update** and **npm auto-update** to add new version automatically, and we prefer to use **npm auto-update** config which is more stable, so could you please consider pushing later released version to npm package? or if it is not convenient for you, we can choose to use **git auto-update** config.

just want to confirm v15.0.2 problem and want to know which auto-update config you prefer.
thank your very much!

https://github.com/cdnjs/cdnjs/pull/9123

**Comment by jasonmayes** [comment]
Hello there, so I prefer to just manage the Git version tags to be honest, I always create a new release when appropriate. I have been without my main PC for a while as moved recently so NPM is a bit o fa pain right now as I have to keep setting up environment

**Comment by jasonmayes** [comment]
PS yes I shall look into updating NPM once I get myself set up again.

**Comment by maruilian11** [comment]
thanks! we use git auto-update now.
