### ISSUE TITLE
How to use with twitter lists?

### ISSUE THREAD

**Issue by MkBeeCtrl** [jasonmayes/Twitter-Post-Fetcher#112]
Hey @jasonmayes , I would like to use your solutions to create a slick carousel with the twitter feed, here's codepen example:

http://codepen.io/Nikolaus91/pen/XNmzmM

Unfortuantely when creating a lists on Twitter page I am not able to see any ID, can you please let me know how can I use your plugin to desplay feed from multiple accounts?

**Comment by MkBeeCtrl** [comment]
As I can see I am only allowed to create widget when creating a search widget, but it allows only one argument like #something to display tweets , I can't see a different way

**Comment by jasonmayes** [comment]
var configList = {
  "list": {"listSlug": 'inspiration', "screenName": 'jason_mayes'},
  "domId": 'exampleList',
  "maxTweets": 5,
  "enableLinks": true, 
  "showUser": true,
  "showTime": true,
  "showImages": true,
  "lang": 'en'
};
twitterFetcher.fetch(configList);
