### ISSUE TITLE
Internet Explorer issue

### ISSUE THREAD

**Issue by MarkStokes-outlook** [jasonmayes/Twitter-Post-Fetcher#113]
Hi,

Has anyone experienced / fixed this issue in Internet Explorer?

![img_0381](https://cloud.githubusercontent.com/assets/17313109/20967896/70173278-bc79-11e6-8876-661eda75f76f.PNG)

All other browsers work perfectly.

Regards,

Mark

**Comment by jasonmayes** [comment]
It seems like the DOM element no longer exists... You sure the element you are trying to inject to exists?

**Comment by MarkStokes-outlook** [comment]
It turned out to be very simple.  The initialisation code needed moving down to the bottom of the page.

Maybe some more elegant error handling and a console message would be nice if the DOM element doesn't exist.
