### ISSUE TITLE
Retweets & source

### ISSUE THREAD

**Issue by buddha82** [jasonmayes/Twitter-Post-Fetcher#114]
Hi,

Found your codepen and got my twitter feed to work as I want. Only one thing doesn't seem to work as I want it to and that is my retweets. De quote I added to it is displayed, but the tweet I retweeted isn't. 

So lets say I retweet TweetA and add Lorem Ipsum as a quote. The quote Lorem Ipsum is displayed, but the source (TweetA) is not. Is this possible with your script?

**Comment by jasonmayes** [comment]
You would have to look at the raw JSON coming back to see if this is a JSON change issue or not - it is possible Twitter changed the format of the JSON so the original is within some different object or such. If it is not working right now, then no it is not currently supported.
