### ISSUE TITLE
Plugin Seems to be down across the board

### ISSUE THREAD

**Issue by pixelsandthings** [jasonmayes/Twitter-Post-Fetcher#115]
Looks like somethings died, any ideas, your site's also effected. Cheers.

**Comment by nmacd85** [comment]
I checked the site I have this one and its good, also checked Jason's demo site and it loads fine. What are you seeing and where exactly?

**Comment by pixelsandthings** [comment]
Looks to have just come backup, it wasn't a one off as a number of clients had the same issue, via 2 different agencies.

**Comment by jasonmayes** [comment]
Maybe Twitter CDN was having issues? Anyone know? I shall close this for now as can not reproduce, but feel free to re open if it comes back
