### ISSUE TITLE
Fetcher fails if twitter username is invalid

### ISSUE THREAD

**Issue by ericbdev** [jasonmayes/Twitter-Post-Fetcher#116]
https://github.com/jasonmayes/Twitter-Post-Fetcher/blob/master/js/twitterFetcher.js#L188

There's an assumption that `data.body` will be present on the `callback`, but `data.body` is `undefined` if the twitter handle is invalid

**Comment by jasonmayes** [comment]
Thanks for reporting this. Have added a check to ensure data.body exists :-)
