### ISSUE TITLE
How to limit ammount of characters in tweets

### ISSUE THREAD

**Issue by DeoThemes** [jasonmayes/Twitter-Post-Fetcher#117]
I'm trying to reduce ammount of characters to show only 70-80 characters. But don't see any option to achieve that.

Your advice could be very helpfull.

**Comment by jasonmayes** [comment]
Simply use javascript substring capabilities to extract the number of chars you desire https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/substring

**Comment by DeoThemes** [comment]
Any idea where to apply it?

I use this code, but it returns text without links.
`$("#tweets .tweet").each(function() {
    $(this).html($(this).text().substring(0, 80));
 });`

**Comment by jasonmayes** [comment]
I dont use jQuery but using raw JavaScript you can just get the innerText of the element that contains the tweet and then apply it to that.

**Comment by DeoThemes** [comment]
That's what it returns and shows in console, it's just fetch the plain text and removes all the html tags.
innerHTML: "Learning to code with HTML and CSS to build a website https://deothemes.com/blog"
innerText:"Learning to code with HTML and CSS to build a website https://deothemes.com/blog"
