### ISSUE TITLE
Documentation references likes instead of lists

### ISSUE THREAD

**Issue by twistofreality** [jasonmayes/Twitter-Post-Fetcher#119]
In your documentation within exampleUsage.js for `@param object.list`, it looks like you forgot to update a part after copying/pasting:

```
 * @param object.list {Object} An object containing a refernece to the
 *     screen name we wish to grab likes for. Should be like this:
 *     {"listSlug": 'inspiration', "screenName": 'jason_mayes'}
```

(see https://github.com/jasonmayes/Twitter-Post-Fetcher/blob/master/js/exampleUsage.js#L30)

I believe "... grab likes for ..." should be "... grab list for ..." in this context.  It should be obvious, but it might be confusing for some.

Also, "reference" is misspelled for profile, likes, and list documentation.

Thanks for tackling this problem.  This saved me a bunch of time setting up OAuth and back-end authentication for a simple front-end task.

**Comment by jasonmayes** [comment]
Thanks for reporting. Updated.
