### ISSUE TITLE
Showing Retweet

### ISSUE THREAD

**Issue by premselvang** [jasonmayes/Twitter-Post-Fetcher#123]
Hi,
The current script is displaying retweet as well. can you please let me know it is normal.
Thanks.

**Comment by jasonmayes** [comment]
See https://github.com/jasonmayes/Twitter-Post-Fetcher/blob/master/js/exampleUsage.js - search for "showRetweet" parameter which you can set to false.

**Comment by premselvang** [comment]
Thank you
