### ISSUE TITLE
enableLinks not working correctly

### ISSUE THREAD

**Issue by jakewhiteley** [jasonmayes/Twitter-Post-Fetcher#124]
If `dataOnly` is set to true, the value of `enableLinks` is ignored, and hashtags are always linked in the tweet content passed to a callback.

If I still use my callback, but set `dataOnly` to false, the passed tweets do not have hashtag links present, but then I cannot format the way I wish without regex/parsing the tweet HTML.

**Comment by jasonmayes** [comment]
I believe this is working as intended. If you request the dataOnly then it will give you the raw tweet innerHTML essentially. So it is then up to you to change it in that case as you desire.
