### ISSUE TITLE
GIFs/Media Other Than Images not displaying

### ISSUE THREAD

**Issue by ItsMichal** [jasonmayes/Twitter-Post-Fetcher#126]
I don't know whether this is a bug, or whether this simply isn't supported, but I can't seem to retrieve GIFs (which I know twitter treats as a video), or media such as videos. If this could be supported, that would be awesome!

Site in question is [michal.us/newclock](http://michal.us/newclock)

**Comment by sebrojas14** [comment]
Smeone? please

**Comment by ilgio** [comment]
please .. the URL of the images not displaying with example8

**Comment by jasonmayes** [comment]
If someone wants to trawl through the JSON and see if this exists and make an extract for it, by all means feel free. I have not had a chance to look at this yet.

**Comment by kguk** [comment]
Hiya - the image pulling functionality appears to have stopped. It was working last night... I'll take a look and see if I can debug, just wondering if you were looking into this? It's looking for 'data-srcset', which doesn't appear to be coming through in the HTML any more. There is a URL to the image provided, but that url seems to be broken when I try following the URL.... :(

**Comment by kguk** [comment]
Okay this piece of code fixes this:

`  function extractImageUrl(image_data) {

    if (image_data !== undefined && image_data.innerHTML.indexOf('data-image') >= 0) {
      console.log("DEBB: data_src:" + image_data.innerHTML);

      var data_src = image_data.innerHTML.match(/data-image=\"([A-z0-9]+:\/\/[A-z0-9]+\.[A-z0-9]+\.[A-z0-9]+\/[A-z0-9]+\/[A-z0-9\-]+)/i)[1];

      return decodeURIComponent(data_src) + ".jpg";
    }

  }`

**Comment by jasonmayes** [comment]
Can that regex be simplified? Looks like it is just looking for URL in data-image instead of srcset right?

**Comment by jasonmayes** [comment]
This is now integrated and resolved. Thanks @kguk for the fix.
