### ISSUE TITLE
Not working with Google Chrome?

### ISSUE THREAD

**Issue by SamMcSam** [jasonmayes/Twitter-Post-Fetcher#127]
It seems like it's not working anymore with current versions of Chrome (I'm running Version 58.0.3029.110 (64-bit)).

The demo page isn't loading anything for me :
http://codepen.io/jasonmayes/pen/Ioype

However, it seems to work fine in Firefox (53.0.2) and Edge.

Is anybody having the same problem?

**Comment by jasonmayes** [comment]
Works for me. Can not replicate your issue.
