### ISSUE TITLE
Twitter Updated: Script not working.

### ISSUE THREAD

**Issue by Hockeyguy1703** [jasonmayes/Twitter-Post-Fetcher#129]
Hello, I am sorry I am not very skilled with code but this has been a great script to use. However, I noticed today that it stopped working and when I downloaded the newest version, I don' t think that version was working either. Did Twitter update it's end making this script not work? It could totally be my issue and if so I'm sorry, but if not, I thought it might be a good idea to point it out.

Thank you

**Comment by Hockeyguy1703** [comment]
Also, and I don't know if this matters or not, But I did just add the iconv php library to my server. Could that be affecting the script?

**Comment by nmacd85** [comment]
Check out issue #128

Twitter was updated so we will need to wait for a fix.

**Comment by Hockeyguy1703** [comment]
Oops, yep I see that now, Thank you, should I close this thread and wait on the #128?

**Comment by jasonmayes** [comment]
Lets put all comments on 128. Thanks for reporting though.

**Comment by jasonmayes** [comment]
Update: Fixed in v17
