### ISSUE TITLE
Feed not working due to MIME type

### ISSUE THREAD

**Issue by tallchap67** [jasonmayes/Twitter-Post-Fetcher#131]
Refused to execute script from 'https://cdn.syndication.twimg.com/widgets/timelines/345170787868762112?&lan…itterFetcher.callback&suppress_response_codes=true&rnd=0.18467069690713034' because its MIME type ('application/json') is not executable, and strict MIME type checking is enabled

Stopped working on my site(s) also giving same error on your demo site,

**Comment by pooley182** [comment]
Just seen this issue on a couple of our sites.

**Comment by tallchap67** [comment]
This is fixed by applying the latest version of the script 17.0
