### ISSUE TITLE
Stopped working on Chrome?

### ISSUE THREAD

**Issue by HairMachine** [jasonmayes/Twitter-Post-Fetcher#132]
Hi there

It seems today all the twitter feeds have stopped working via this API on Chrome. It was working fine yesterday when I was working on it.

Chrome version is 58.0.3029.110 (64-bit)

Error is:

Refused to execute script from 'https://syndication.twitter.com/timeline/profile?callback=twitterFetcher.ca…en_name=ProfileName&suppress_response_codes=true&lang=en&rnd=0.3889037481709985' because its MIME type ('application/json') is not executable, and strict MIME type checking is enabled.

Not sure yet if this is a new Chrome issue, Twitter made a change to something on their server, or it's just a temporary glitch.

**Comment by christchan** [comment]
It is only on Chrome I think, I have checked on my Safari and Firefox and the same error occurs. 

Below is the error that I received.

> SyntaxError: Unexpected token ':'. Parse error.

**Comment by madeingnecca** [comment]
I was experiencing the same issue, but it disappeared by using the latest version (v17).

**Comment by HairMachine** [comment]
@madeingnecca - yep, you're right - updating to 0.17 indeed fixes this. Thanks a ton!

**Comment by christchan** [comment]
@madeingnecca Thank you so much. upgrading to 17 has fixed my problem.

**Comment by jasonmayes** [comment]
As you have found out I have already pushed an update for this issue fixed in bug 128.
