### ISSUE TITLE
MIME type ('application/json') is not executable

### ISSUE THREAD

**Issue by alifeinbinary** [jasonmayes/Twitter-Post-Fetcher#133]
I've been developing a new portfolio site and had tweetFetcher working flawlessly up until a couple of days ago I started getting this error. I don't believe I've changed anything in my code that would cause this to happen. Your Codepen examples are still working so I can only assume that it's something at my end. 

Chrome produces this - 
Refused to execute script from 'https://syndication.twitter.com/timeline/profile?callback=twitterFetcher.ca…=alifeinbinary&suppress_response_codes=true&lang=en&rnd=0.6799931159990922' because its MIME type ('application/json') is not executable, and strict MIME type checking is enabled.\

Firefox produces this - 
SyntaxError: missing ; before statement[Learn More]

Safari produces this - SyntaxError: Unexpected token ':'. Parse error.
`
{
    "headers": {
        "status": 200,
        "maxPosition": "865244219014762496",
        "minPosition": "845399828897017856",
        "xPolling": 30,
        "time": 1495309386
    },
    " HTML of tweet response "
}
`

**Comment by MaMaRo123** [comment]
please look at #132 and update to version 17
