### ISSUE TITLE
MIME type error

### ISSUE THREAD

**Issue by cho9e** [jasonmayes/Twitter-Post-Fetcher#134]
As of about yesterday I keep getting this error.
`Refused to execute script from 'https://syndication.twitter.com/timeline/profile?callback=twitterFetcher.ca…_name=rarings&suppress_response_codes=true&lang=en&rnd=0.42517474931215715' because its MIME type ('application/json') is not executable, and strict MIME type checking is enabled.`

[I found this in the twitter forum on the same topic.](https://twittercommunity.com/t/mime-type-error-when-getting-tweet-json-data/87484/5)

**Comment by jasonmayes** [comment]
See the version 17 which fixes this issue already.
