### ISSUE TITLE
Failed to execute script

### ISSUE THREAD

**Issue by MkBeeCtrl** [jasonmayes/Twitter-Post-Fetcher#135]
On couple of different websites on 3 different hosting providers we started to receive the following
error: 

Refused to execute script from 'https://syndication.twitter.com/timeline/profile?callback=twitterFetcher.ca…Kancelaria_DSK&suppress_response_codes=true&lang=pl&rnd=0.5761728988529558' because its MIME type ('application/json') is not executable, and strict MIME type checking is enabled.

is this an issue related to your Fetcher? We did not work on mentioned websites in any code realted way. 

All of those pages are running 16.02, we are going to update your script but we are looking for a quick fix right now.

**Comment by joesecurity** [comment]
+1

**Comment by jasonmayes** [comment]
Guys please see bug 128, you must use v17 to solve this issue.
