### ISSUE TITLE
Getting Uncaught TypeError

### ISSUE THREAD

**Issue by iamshipon1988** [jasonmayes/Twitter-Post-Fetcher#136]
Hey I'm trying to integrate this into a project and everytime I try to create any of the samples you demo'd I get `Uncaught TypeError: Cannot set property 'innerHTML' of null`. See image below:

I'm using this line of code to pull it
```
var configMentions = {
  "id": '{WIDGET_CODE}',
  "domId": 'twitterMentions',
  "maxTweets": 12,
  "enableLinks": true,
  "showUser": true,
  "showTime": true,
  "lang": 'en'
};
twitterFetcher.fetch(configMentions);
```
Any idea why?

<img width="742" alt="screen shot 2017-05-22 at 8 00 49 pm" src="https://cloud.githubusercontent.com/assets/4104178/26333160/9779624a-3f29-11e7-9166-628f7fbbcbf8.png">

**Comment by jasonmayes** [comment]
It means the element you are trying to inject the content into does not exist. Make sure you call twitter fetcher *after* the DOM element has been created only.

**Comment by iamshipon1988** [comment]
Noticed that issue after I posted. Sorry forgot to close this. Thanks!
