### ISSUE TITLE
Is it possible to handle cache in order to save requests to https://cdn.syndication.twimg.com...

### ISSUE THREAD

**Issue by monecchi** [jasonmayes/Twitter-Post-Fetcher#137]
Browsing an old commit there used to have a caching config. Is this deprecated? Anyways of setting a cache and save requests to https://cdn.syndication.twimg.com...?

I'd really appreciate any inputs regarding this issue.

**Comment by franklinjavier** [comment]
@monecchi you need to update to v17.0.0

**Comment by franklinjavier** [comment]
@jasonmayes tks for the fix

**Comment by monecchi** [comment]
@franklinjavier Thanks for the input, I've already update to the latest version, but I jut can't see in the docs any options to enable cache, do I have to make changes to the plugin itself?

**Comment by jasonmayes** [comment]
As far as I remember I did not cache anything locally as to get new tweets you must fetch the new version from the server. When you call fetch I assume you want the latest data.
