### ISSUE TITLE
Doesn't display any tweets

### ISSUE THREAD

**Issue by i-bajrai** [jasonmayes/Twitter-Post-Fetcher#138]
Refused to execute script from 'https://syndication.twitter.com/timeline/profile?callback=twitterFetcher.ca…name=RR_Stars&suppress_response_codes=true&lang=en&rnd=0.39741092527278976' because its MIME type ('application/json') is not executable, and strict MIME type checking is enabled.

**Comment by kmbn** [comment]
You just need to update to v17. This issue has already been documented and resolved here: https://github.com/jasonmayes/Twitter-Post-Fetcher/issues/128
