### ISSUE TITLE
Not working with Chrome v58 even using 17.0.0

### ISSUE THREAD

**Issue by NedYork** [jasonmayes/Twitter-Post-Fetcher#139]
Seems like this library is not compatible with chrome v58 even using v17.0.0 of this library. Works fine in all other browsers and after downgrading to Chrome v57, all works again. Anybody else having this same issue?

**Comment by NedYork** [comment]
Seems to be a chrome extension that was interfering with the functionality.

**Comment by jasonmayes** [comment]
Thanks for updating the thread :-)
