### ISSUE TITLE
Emojis no longer coming through as <img>

### ISSUE THREAD

**Issue by anoffsinger** [jasonmayes/Twitter-Post-Fetcher#142]
I'm noticing after updating to the latest release that emoji aren't coming through with tweet data. Previously, I believe they came through in an <img> tag.

This may be related to the earlier issue calling out GIF issues. 

Site in questions is: http://noff.me/

**Comment by mikedodd** [comment]
I to can repeat this, have tried various data settings and cannot repeat, anyone have an idea of where to look? @anoffsinger did you have any joy

**Comment by mikedodd** [comment]
Hey I have a pull request in here for this
https://github.com/jasonmayes/Twitter-Post-Fetcher/pull/148

**Comment by jasonmayes** [comment]
Thank you @mikedodd  shall take a look now.
