### ISSUE TITLE
MIME type error

### ISSUE THREAD

**Issue by markbain** [jasonmayes/Twitter-Post-Fetcher#143]
Seeing the following error: 

`Refused to execute script from 'https://cdn.syndication.twimg.com/widgets/timelines/XXXXXXXXXXXXX?&lan…witterFetcher.callback&suppress_response_codes=true&rnd=0.7214045377487386' because its MIME type ('application/json') is not executable, and strict MIME type checking is enabled.`

There's a recent thread [here](https://twittercommunity.com/t/mime-type-error-when-getting-tweet-json-data/87484/15) that repeatedly points out that [cdn.syndication.twimg.com](https://cdn.syndication.twimg.com)

> is not a supported or documented API endpoint

**Comment by nmacd85** [comment]
Update to version 17. Should resolve the issue.
