### ISSUE TITLE
Refused to execute script

### ISSUE THREAD

**Issue by hwdavidward** [jasonmayes/Twitter-Post-Fetcher#144]
This issue seems to have crept up recently and I'm hoping someone has a solution. It looks like the MIME type being returned is in error. Any suggestions?

Console Log:
`Refused to execute script from 'https://cdn.syndication.twimg.com/widgets/timelines/654316259878793216?&lan…witterFetcher.callback&suppress_response_codes=true&rnd=0.3573606539644665' because its MIME type ('application/json') is not executable, and strict MIME type checking is enabled.`

**Comment by jasonmayes** [comment]
Please always use latest version of twitter fetcher before reporting bugs which are already fixed :-)
