### ISSUE TITLE
Feed pulling 5 tweets from other feeds

### ISSUE THREAD

**Issue by nathancoffey** [jasonmayes/Twitter-Post-Fetcher#145]
This plugin quit working for a client and while the word 'Twitter' is pointing to the correct twitter account, the 5 tweets it is pulling come from 5 different accounts and not ours. The account is @gothamorg but the feed is showing 5 random tweets with the word Gotham in them. 

Look at the bottom of http://www.gothamorg.com/about

this is the code we have: http://prntscr.com/fknx9b

**Comment by jasonmayes** [comment]
We stopped supporting widget IDs a long time ago. Please try and use the new example:

var configProfile = {
  "profile": {"screenName": 'jason_mayes'},
  "domId": 'example',
  "maxTweets": 5,
  "enableLinks": true, 
  "showUser": true,
  "showTime": true,
  "showImages": true,
  "lang": 'en'
};
twitterFetcher.fetch(configProfile);
