### ISSUE TITLE
Windows Defender reporting a virus

### ISSUE THREAD

**Issue by davidgebbett** [jasonmayes/Twitter-Post-Fetcher#147]
Just a heads up, with the new Windows Defender Security Center in the creators edition update to Windows 10, it blocks the plugin from downloading.

It says that the 'exampleUsage.js' file contains 'Trojan:Win32/Sprisky.X!cl'
https://www.microsoft.com/security/portal/threat/encyclopedia/Entry.aspx?Name=Trojan:Win32/Sprisky.X!cl

**Comment by jasonmayes** [comment]
I am not sure how that is possible as JavaScript is a safe language and can not access any files on a computer etc by itself. Thanks for the report, though I have no idea why it would think a JS file is a trojan... And the example usage file too?! There is no code in there that even does anything fancy!
