### ISSUE TITLE
Refused to execute script from 'https://cdn.syndication.twimg.com/widgets/timelines/345170787868762112?&lan…witterFetcher.callback&suppress_response_codes=true&rnd=0.2864229594762411' because its MIME type ('application/json') is not executable, and strict MIME type checking is enabled.

### ISSUE THREAD

**Issue by Factored-Dan** [jasonmayes/Twitter-Post-Fetcher#149]
Hi guys. Can anyone help with the following error:

Refused to execute script from 'https://cdn.syndication.twimg.com/widgets/timelines/345170787868762112?&lan…witterFetcher.callback&suppress_response_codes=true&rnd=0.2864229594762411' because its MIME type ('application/json') is not executable, and strict MIME type checking is enabled.

I've updated to version Twitter Post Fetcher v17.0.1 and still receive the error.
![screen shot 2017-07-05 at 09 58 13](https://user-images.githubusercontent.com/16665912/27857200-acb53e02-6168-11e7-9532-30cea5936c3e.png)
<img width="1273" alt="screen shot 2017-07-05 at 09 57 45" src="https://user-images.githubusercontent.com/16665912/27857201-acb80218-6168-11e7-8e81-5b1231b2be47.png">

**Comment by MarkStokes-outlook** [comment]
We are also experiencing this issue.  Does anyone know of a resolution?

**Comment by davidgebbett** [comment]
I had the same issue, but I was on V15, as soon as I updated to V17 it worked for me, I assume JSON mime type is allowed through your server?

**Comment by jasonmayes** [comment]
You have to use the latest version guys. Something changed Twitter side.

**Comment by Factored-Dan** [comment]
Thanks for you replies guys. @jasonmayes I'm on the latest version - v17.0.1 ? Please see my screenshots on the comments above.

**Comment by jasonmayes** [comment]
Hmmm that is odd, it is working for me: http://jasonmayes.com/projects/twitterApi/ What config are you using? Can you try editing this fiddle with your call to twitterFetcher to see if it works here:  https://codepen.io/jasonmayes/pen/Ioype

**Comment by jasonmayes** [comment]
Ah, it appears you are using widget ID, whilst the code is still there for it as it was working, it seems widget ID no longer works. Try the new call using the user id instead? See example usage js file.

**Comment by jasonmayes** [comment]
Update: Looking at the file you have imported you are actually using version 15.0 see: https://arndalemorecambe.co.uk/modules/mod_opening_times/assets/js/twitterFetcher_min.js

**Comment by Factored-Dan** [comment]
Hi @jasonmayes. My bad, there seemed to be a reference to an old version on the website as well as the new version I was using, loading both scripts causing an issue. I can confirm the script is now working. Thank you for your help

**Comment by jasonmayes** [comment]
No problem :-)

**Comment by HenryCullen** [comment]
Hi @jasonmayes , did you find a solution to this. I'm having the same issue with a twitter widget on my side. It works perfectly in the local html file but when I open the github website it only displays "Tweets By [User]"
