### ISSUE TITLE
Adapting to get/trends by WOEID

### ISSUE THREAD

**Issue by oscady** [jasonmayes/Twitter-Post-Fetcher#152]
Hello

First of all, this is fantastic. I've done a lot of searching for help getting twitter data in the browser so thank you for your detail and examples.

I was wondering if I could adapt this code to show saw the top 10 trending topics for a specific WOEID? I'm quite new to javascript and very new to the twitter API, but I've been surprised at how hard I've found it to do what I thought would be a fairly simple task.

Any thoughts on this would be much appreciated

Oscar

**Comment by jasonmayes** [comment]
Unless this is specified in the JSON package that is returned it will not be possible unless you have somehow curated a list on twitter that does this automatically then you can just pull that list in using TwitterFetcher.
