### ISSUE TITLE
Cannot Create Widget in Twitter

### ISSUE THREAD

**Issue by wireframe74** [jasonmayes/Twitter-Post-Fetcher#153]
Hi It seems Twitter no longer allows you to create a widget with an associated ID. Is there any way in which to get around this if you don't have a widget created with old API?

**Comment by wireframe74** [comment]
From here a few others had the same issue it seems with this plugin:

https://twittercommunity.com/t/how-can-i-get-a-twitter-widget-id/68917/17

**Comment by jasonmayes** [comment]
Please read the latest documentation which explains how not to use an ID. https://github.com/jasonmayes/Twitter-Post-Fetcher/blob/master/js/exampleUsage.js
