### ISSUE TITLE
Custom Tweet Markup

### ISSUE THREAD

**Issue by BHWD** [jasonmayes/Twitter-Post-Fetcher#154]
I am looking for a way to change the output markup so that the twitter name and username are above the tweet text with the profile image to the left. I am trying to replicate the twitter.com tweet layout. Is this possible?

**Comment by jasonmayes** [comment]
Yes, see advanced examples which allow you to specify a custom callback function to which to pass the raw tweet data so you can format as you wish.

**Comment by BHWD** [comment]
@jasonmayes I saw that example but from what I can see you cannot specify the markup for the actual tweet? You can define the list item but the tweet contents is one object?

**Comment by jasonmayes** [comment]
You can use the object that is passed to create whatever markup you desire. Unless I am not understanding your question?
