### ISSUE TITLE
Refuse to execute script

### ISSUE THREAD

**Issue by AmyScript** [jasonmayes/Twitter-Post-Fetcher#155]
Hi,
I ran into an error when using the code:
Refused to execute script from 'https://cdn.syndication.twimg.com/widgets/timelines/....' because its MIME type ('application/json') is not executable, and strict MIME type checking is enabled.

So I had to modify code for it to return a JSONP object instead using this: https://json2jsonp.com/

Is there any other way around this?

Thanks!

**Comment by jasonmayes** [comment]
You need to use the latest version of Twitter Fetcher. This has been fixed.
