### ISSUE TITLE
Error in Firefox not in chrome

### ISSUE THREAD

**Issue by codingarrow** [jasonmayes/Twitter-Post-Fetcher#158]
Loading failed for the <script> with source “https://syndication.twitter.com/timeline/profile?callback=__twttrf.callback&dnt=false&screen_name=jason_mayes&suppress_response_codes=true&lang=en&rnd=0.0440598888430922”.

This happens in Firefox Quantum 57.0.1 (64-bit) the tweets aren't loaded / In chrome & safari it works fine

**Comment by jasonmayes** [comment]
Trying in latest version of FF, I dont have any issues, Checked in 57.0.2 (64-bit). Can not replicate.
