### ISSUE TITLE
Refused to execute script 

### ISSUE THREAD

**Issue by pierrebonbon** [jasonmayes/Twitter-Post-Fetcher#159]
I've started getting this error (on Chrome) after a while:

>Refused to execute script from 'https://cdn.syndication.twimg.com/widgets/timelines/***?&lang=en&callback=twitterFetcher.callback&suppress_response_codes=true&rnd=0.28092645613159695' because its MIME type ('application/json') is not executable, and strict MIME type checking is enabled.

Any clues on what may be wrong?

**Comment by jasonmayes** [comment]
Are you using the latest version of the Twitter Fetcher? I believe this was fixed a while back?

**Comment by pierrebonbon** [comment]
@jasonmayes updating Twitter Fetcher worked out perfectly. Thank you so much for the hint! Ohh, and my apologies too for bothering you with such a dumb issue!
