### ISSUE TITLE
Refused to execute script

### ISSUE THREAD

**Issue by twoonk** [jasonmayes/Twitter-Post-Fetcher#162]
Any idea why I get this with the latest version 17.0.3? Earlier issues like this should be resolved with the 17.-versions?

> Refused to execute script from 'https://cdn.syndication.twimg.com/widgets/timelines/33323849?&lang=en&callback=__twttrf.callback&suppress_response_codes=true&rnd=0.9266545497017604' because its MIME type ('application/json') is not executable, and strict MIME type checking is enabled.

Tried with other examples as well (without ID)

**Comment by jasonmayes** [comment]
https://codepen.io/jasonmayes/pen/Ioype
Everything is working for me... Are you sure you are using the latest version?
