### ISSUE TITLE
Consider adding aria-labelledby to .timePosted for accessibility

### ISSUE THREAD

**Issue by adamjohnson** [jasonmayes/Twitter-Post-Fetcher#163]
![Example of where to use aria-labelledby on Tweet time](https://user-images.githubusercontent.com/575865/37054644-66e2b54e-214d-11e8-9b39-8744ba9b4766.png)

## Steps to reproduce the issue

  1. Use Twitter Post Fetcher and output tweets with `.timePosted` visible.
  1. Make sure multiple tweets from the same day are visible (like in the image above).

## Results

Twitter Post Fetcher will output links like "Posted on March 1, 2018" for each tweet posted on March 1st.

## Request

WCAG 2.0 suggests links with the same link text to use either `aria-labelledby` or `aria-label`. Would you consider adding `aria-labelledby` to `.timePosted`? The `aria-labelledby` can point to `.tweet`.

Here's [the spec](https://www.w3.org/TR/WCAG20/#navigation-mechanisms-refs). The [Siteimprove Chrome Extension](chrome.google.com/webstore/detail/siteimprove-accessibility/efcfolpjihicnikpmhnmphjhhpiclljc) is a great tool to help test accessibility issues like this. [MDN Docs](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_aria-labelledby_attribute) for `aria-labelledby`.

**Comment by jasonmayes** [comment]
This is simply taking whatever Twitter passes back to us int he JSON object and outputs that. If you want to re-format you would need to write a custom function to call upon all date fields returned.

**Comment by jasonmayes** [comment]
Oh wait you are saying to add that class to our output?

**Comment by adamjohnson** [comment]
This is what we implemented:

https://www.diffchecker.com/c6wmeUaz 

The tweet receives an `id`, then the `aria-labelledby` is added to the anchor tag for the time posted.

Here's an HTML example:

```html
<ul>
  <li>
    <p class="tweet" id="tweet--1">Hey, this is my first tweet!</p>
    <p class="timePosted">
      <a href="#" aria-labelledby="tweet--1">Posted on Mar 8, 2018</a>
    </p>
  </li>

  <li>
    <p class="tweet" id="tweet--2">This is my second tweet.</p>
    <p class="timePosted">
      <a href="#" aria-labelledby="tweet--2">Posted on Mar 8, 2018</a>
    </p>
  </li>
</ul>
```

**Comment by jasonmayes** [comment]
Closing as this can be achieved using advanced example and constructing own html if needed.
