### ISSUE TITLE
Slick Slider is not working on tweet fetcher please help

### ISSUE THREAD

**Issue by AsadAlihp** [jasonmayes/Twitter-Post-Fetcher#164]
First of all all I love twitter post fetcher alot it really simple and easy to implement but for last two days I have been struggling to integrate it with slick (a slider) but slider is not working.

**Comment by jasonmayes** [comment]
There is a known issue. Hopefully will be fixed soon, check back for latest version.

**Comment by jasonmayes** [comment]
I have written a a patch to deal with this change. Please update to v18.0.0
