### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getAttribute' of undefined

### ISSUE THREAD

**Issue by Tombarr** [jasonmayes/Twitter-Post-Fetcher#165]
Twitter Post Fetcher v17.0.3 appears to be crashing, including on the [Codepen demos](http://codepen.io/jasonmayes/pen/Ioype). Currently the stack trace points to this method:

```Uncaught TypeError: Cannot read property 'getAttribute' of undefined at swapDataSrc```

```
function swapDataSrc(element) {
    var avatarImg = element.getElementsByTagName('img')[0];
    avatarImg.src = avatarImg.getAttribute('data-src-2x');
    return element;
}
```

From `callback`:

```
if (printUser) {
     authors.push(swapDataSrc(tmp[x].getElementsByClassName('timeline-Tweet-author')[0]));
}
```

**Comment by azcotic** [comment]
I have the same issue. In two differents Webs.

**Comment by b3smith13** [comment]
I've got a few sites with broken twitter feeds right now from the same error.

**Comment by jdebuchy** [comment]
@Tombarr posted a solution here. Thanks!
https://github.com/jasonmayes/Twitter-Post-Fetcher/pull/166

**Comment by deepsoul** [comment]
same issue here

**Comment by jasonmayes** [comment]
I have written a a patch to deal with this change. Please update to v18.0.0
