### ISSUE TITLE
Twitter-Post-Fetcher not working

### ISSUE THREAD

**Issue by TheSeen** [jasonmayes/Twitter-Post-Fetcher#168]
Hi ... sure you know already but just in case, all twitter post fetches are not working (including your own on your twitter api demo page).

Are you looking into this and will there be an update to fix the issue?

Cheers - keep up the good work.

**Comment by kauffmanes** [comment]
^^ It broke for me as well yesterday/.

**Comment by jasonmayes** [comment]
Thanks for reporting this is a duplicate see 165.

**Comment by jasonmayes** [comment]
I have written a a patch to deal with this change. Please update to v18.0.0
