### ISSUE TITLE
Please update NPM package to latest

### ISSUE THREAD

**Issue by goran-pavlovski** [jasonmayes/Twitter-Post-Fetcher#172]
Hi Jason
Please update the latest version on NPM to 18.0.0
You have done a wonderful job on this one!
Thanks

**Comment by jasonmayes** [comment]
Done!

**Comment by adamjohnson** [comment]
The latest version/tag showing on [npmjs.org](https://www.npmjs.com/package/twitter-fetcher) is 18.0.2.

@jasonmayes Can you run an [`npm publish`](https://docs.npmjs.com/updating-your-published-package-version-number)? 👏

**Comment by jasonmayes** [comment]
Done
