### ISSUE TITLE
Still an issue with "dataOnly": true

### ISSUE THREAD

**Issue by eastface** [jasonmayes/Twitter-Post-Fetcher#173]
Thanks for the usual quick fix.  I think there is still an issue when using "dataOnly": true.  Testing with your Advanced example 3 (config 8) I get:

twitterFetcher.js:317 Uncaught TypeError: Cannot read property 'getAttribute' of null
    at Object.callback (twitterFetcher.js:317)

For me it works fine to comment out that line.  I still get avatars.  Reading some of the comments around v18.0.0 I suspect this line is now redundant and was just overlooked.

Thanks again.

**Comment by jasonmayes** [comment]
Fixed in 18.0.1 thanks for letting me know!
