### ISSUE TITLE
Version 18.01 not working on IE 11 and Edge

### ISSUE THREAD

**Issue by goran-pavlovski** [jasonmayes/Twitter-Post-Fetcher#174]
Object doesn't support property or method 'prepend'
Error happens in the latest version, there was no such issue before

**Comment by jasonmayes** [comment]
Is there a reason you closed this?

**Comment by jasonmayes** [comment]
Update: Fixed prepend issue in 18.0.2 :-) Added polyfill.

**Comment by goran-pavlovski** [comment]
Hah sorry i was in a hurry, i added a polyfill also so i closed it :)
Thanks anyway

**Comment by jasonmayes** [comment]
I also added the poly :-) All fixed.
