### ISSUE TITLE
Generate other widget type than "search" on tw is not allowed anymore

### ISSUE THREAD

**Issue by dvorapa** [jasonmayes/Twitter-Post-Fetcher#175]
I used to use Twitter Fetcher to get tweets without replies from some twitter account. But now if I try to create a new widget, It says some warning first and then redirects me to https://publish.twitter.com/# where no widget id is created anymore.

The only option is to generate search widget. But I also get replies into the list. Could you help?

**Comment by dvorapa** [comment]
Sorry, found you've solved the issue already

**Comment by jasonmayes** [comment]
No problem :-)
