### ISSUE TITLE
Uncaught ReferenceError

### ISSUE THREAD

**Issue by webguy262** [jasonmayes/Twitter-Post-Fetcher#178]
We use Twitter Fetcher to display tweets in the "chatter" grid toward the bottom of the homepage of [this site](http://www.bigmouthinc.com/).

Twitter Fetcher stopped working so I upgraded to the latest versions of twitterFetcher_min.js and exampleUsage.js (your default one).

However, I'm still getting the error:

```
exampleUsage.js:85 Uncaught ReferenceError: twitterFetcher is not defined
    at exampleUsage.js:85
```

I also did a test page [here](http://brinsterinc.com/twitfetch.html) and am getting this error:

```
Uncaught TypeError: Cannot set property 'innerHTML' of null
    at handleTweets (twitterFetcher_min.js:12)
    at Object.callback (twitterFetcher_min.js:66)
    at list?callback=__twttrf.callback&dnt=false&list_slug=inspiration&screen_name=jason_mayes&suppress_response_codes=true&lang=en&rnd=0.48398372253476585:1
```

What am I missing?

**Comment by jasonmayes** [comment]
Sounds like you have not included the code properly and/or the HTML element you are trying to inject stuff into does not exist before the call to Twitter Fetcher
