### ISSUE TITLE
Can you take a look

### ISSUE THREAD

**Issue by webguy262** [jasonmayes/Twitter-Post-Fetcher#179]
I wrote here the other day about TwitterFetcher not working [here](http://www.bigmouthinc.com/).

I posted about then issue on SO and get [this reply](https://stackoverflow.com/questions/50701604/referenceerror-twitterfetcher-is-not-defined)

Can you advise on a fix that will get TwitterFetcher working?

**Comment by jasonmayes** [comment]
In the HTML you import Twitter Fetcher and after that you then try and reference it right?

**Comment by jasonmayes** [comment]
What happens if you put the call to twitter Fetcher in the same file as Twitter Fetcher itself?

var config1 = {
  "profile": {"screenName": 'bigmouthinc_'},
  "domId": 'example1',
  "maxTweets": 2,
  "enableLinks": true,
  "showUser": false,
  "showInteraction": false
};
twitterFetcher.fetch(config1);

**Comment by jasonmayes** [comment]
Oh wait as the guy said it appears you have AMD on your site which is deferring the loading of twitterFetcher. Yes I think if you remove the AMD stuff it should be fine.

**Comment by jasonmayes** [comment]
Here is TwitterFetcher without the extra checks:
https://jsfiddle.net/jfqhmv0b/

**Comment by webguy262** [comment]
Same error, just points to the call in twitterFetcher_min:
ReferenceError: twitterFetcher is not defined http://www.bigmouthinc.com/wp-content/themes/bmi/js/twitterFetcher_min.js:77
It's on the site that way now if you want to look.
Thanks for you help!


    On Wednesday, June 6, 2018, 4:28:37 PM EDT, Jason Mayes <notifications@github.com> wrote:  
 
 
What happens if you put the call to twitter Fetcher in the same file as Twitter Fetcher itself?

var config1 = {
"profile": {"screenName": 'bigmouthinc_'},
"domId": 'example1',
"maxTweets": 2,
"enableLinks": true,
"showUser": false,
"showInteraction": false
};
twitterFetcher.fetch(config1);

—
You are receiving this because you authored the thread.

Reply to this email directly, view it on GitHub, or mute the thread.:

| 
| 
| 
|  |  |

 |

 |
| 
|  | 
Can you take a look · Issue #179 · jasonmayes/Twitter-Post-Fetcher

I wrote here the other day about TwitterFetcher not working here. I posted about then issue on SO and get this r...
 |

 |

 |





| 
| 
| 
|  |  |

 |

 |
| 
|  | 
Build software better, together

GitHub is where people build software. More than 28 million people use GitHub to discover, fork, and contribute ...
 |

 |

 |






ReferenceError: twitterFetcher is not defined http://www.bigmouthinc.com/wp-content/themes/bmi/js/twitterFetcher_min.js:77

**Comment by jasonmayes** [comment]
You got it working using my modified script yes? See above.

**Comment by webguy262** [comment]
Yes, the modified script fixed the issue. Thank you very much!
