### ISSUE TITLE
screenName not working?

### ISSUE THREAD

**Issue by porchemasi** [jasonmayes/Twitter-Post-Fetcher#180]
The examples do not work for anything with screen names. only the deprecated Id examples work. Did something change? All I want to show is my outbound tweets without an iframe.

var configLikes = {
  "likes": {"screenName": 'jason_mayes'},
  "domId": 'exampleLikes',
  "maxTweets": 3,
  "enableLinks": true, 
  "showUser": true,
  "showTime": true,
  "showImages": true,
  "lang": 'en'
};
twitterFetcher.fetch(configLikes);

**Comment by jasonmayes** [comment]
Works for me. I can not replicate: https://codepen.io/jasonmayes/pen/Ioype?editors=0110 Please check something on your website is not conflicting.
