### ISSUE TITLE
Access to protected account

### ISSUE THREAD

**Issue by remimarenco** [jasonmayes/Twitter-Post-Fetcher#184]
Hi!

Thanks a lot for this library, it is very useful to quickly grab some tweets and do experiments. The library was working very well for us, until we decided to change the twitter account to a "protected" mode.
We needed this because we would want to use our twitter account as a curated platform we will display via a video projector (so no access via twitter directly).

Do you think there is a way to insert credentials when requesting the timeline through "syndication.twitter.com"?

Thanks a lot for the help!

**Comment by jasonmayes** [comment]
Unfortunately not that I am aware of.  If you find a way though feel free to make a PR. In this usecase you are best off just writing some server side code to use the official twitter API (which should be used). This component only exists for people who only have front end code and had trouble migrating over to a server side oauth situation. If you are going to do auth then just use the official API?
