### ISSUE TITLE
Cannot see recent tweets using code whilch was working earlier

### ISSUE THREAD

**Issue by lot5sharepoint** [jasonmayes/Twitter-Post-Fetcher#187]
Hi,

We are using Twitter-Post-Fetcher (17.0.0) code to fetch the tweets on SharePoint site using custom webpart. Everything was working until Friday (21 Sept), however it is now not showing any tweets.

URL which gets generated in code:
https://cdn.syndication.twimg.com/widgets/timelines/487093262310588417?&lang=en&callback=__twttrf.callback&suppress_response_codes=true&rnd=0.12443617497249837

When we open above link in browser we get blank jsonp file.

Also when we open below link, it only shows Query 1: My latest tweet. It shows blank in Query 2 and 3.
https://codepen.io/jasonmayes/pen/Ioype

Please confirm if you have made any changes or do we have to make any change in our code?
![error](https://user-images.githubusercontent.com/43537383/45947457-d6619180-bfe3-11e8-8c31-0ef66cf9a0a7.jpg)

**Comment by Kolumbz** [comment]
It seems that Twitter have finished deprecating widgets.

[There was an update 14 days ago from daniel_jin stating: "Update: This deprecation is complete as of September 10, 2018."](https://twittercommunity.com/t/deprecating-widget-settings/102295/2 )

**Comment by nicodemus777** [comment]
We experiencing the same as of September 21st.  Getting this message:

Refused to execute script from 'https://cdn.syndication.twimg.com/widgets/timelines/623169563044089857?&lang=en&callback=__twttrf.callback&suppress_response_codes=true&rnd=0.29911372258621727' because its MIME type ('') is not executable, and strict MIME type checking is enabled.

We tried using the screen name to no avail.   nphares@meridiancity,org

**Comment by tomwake** [comment]
Same issue here too with the console error - Refused to execute script ... because its MIME type ('') is not executable, and strict MIME type checking is enabled.

**Comment by pierrebonbon** [comment]
I guess that I'm bumping on the same issue. I'm getting this: `Loading failed for the <script> with source “https://cdn.syndication.twimg.com/widgets/timelines/...`

**Comment by nicodemus777** [comment]
Thanks for the thread link lot5/Jason/DesignerDave!  It fixed the issue. Kind regards!
