### ISSUE TITLE
Twitter Fetcher error using code whilch was working earlier

### ISSUE THREAD

**Issue by thesheepman** [jasonmayes/Twitter-Post-Fetcher#188]
Code was working for a month, console started throw error 2 days ago:
https://puu.sh/BESTV/38c8cbe0d3.png

**Comment by thesheepman** [comment]
twitterFetcher.js:92 Uncaught TypeError: Cannot read property 'length' of null
    at extractImagesUrl (twitterFetcher.js:92)
    at Object.callback (twitterFetcher.js:416)
    at profile?callback=__twttrf.callback&dnt=false&screen_name=nkn_org&suppress_response_codes=true&lang=en&rnd=0.06964339669674868:1

**Comment by thesheepman** [comment]
I have identified the problem: just flagged ` "showImages": false` and it work again. Probably, there's a bug of retweeted images or smth. [Codepen](https://codepen.io/thesheepman/pen/xyZywp).

**Comment by jasonmayes** [comment]
Twitter deprecated widget ID support so must use the newer form of using username etc now as shown in exampleUsage.js
