### ISSUE TITLE
Retweet with comment

### ISSUE THREAD

**Issue by AvengerDr** [jasonmayes/Twitter-Post-Fetcher#189]
Hi, hopefully I'm not missing anything obvious, but it seems that the retweeted tweet is missing in cases when you "retweet with comment". Only the newer comment appears, but I don't see anything in the resulting object that relates to the tweet that was retweeted.

Will this be supported?

**Comment by jasonmayes** [comment]
I believe due to the changes and deprecation of widgets this is not accessible. You will need to use the OAUTH API which is the official one from Twitter.
