### ISSUE TITLE
Newlines in tweets ignored

### ISSUE THREAD

**Issue by jamieburchell** [jasonmayes/Twitter-Post-Fetcher#193]
Version: 18.0.2

Given a Tweet with example content:

> This is my tweet text. Find out more below
>
> http://www.example.com

The content of the Tweet from Twitter-Post-Fetcher becomes:

> This is my tweet text. Find out more belowhttp://www.example.com

**Comment by jasonmayes** [comment]
Does the returned JSON have a new paragraph tag or such and Twitter fetcher is stripping this or is this just something Twitter is not sending in the JSON?

**Comment by jamieburchell** [comment]
Actually, it looks like there are no whitespace characters between the text and the link, so presumably Twitter is not sending this in the JSON ;(

JSON snippet from `p.timeline-Tweet-text`:

`...retail products!<a href...`

**Comment by jasonmayes** [comment]
Correct this is a Twitter thing. Closing as unfixable via here. You would need to target in CSS somehow to make the link on new line if you wanted it like that or in custom callback function you can inject a break yourself.
