### ISSUE TITLE
AdBlock blocks the library

### ISSUE THREAD

**Issue by GokhanArik** [jasonmayes/Twitter-Post-Fetcher#202]
Hi,

When AdBlocker is on, the library is blocked. Has anyone else this issue before or has a solution for this?

**Comment by jasonmayes** [comment]
First time I have heard of this. No idea how to deal with that... Not sure why though it is not an advert unless someone used it in one somehow.

**Comment by jasonmayes** [comment]
Closing as I can not effect this myself. You will need to talk to the ad blocker people.
