### ISSUE TITLE
MIME type is not executable

### ISSUE THREAD

**Issue by codepuncher** [jasonmayes/Twitter-Post-Fetcher#203]
Looks like this has happened many times in the past (#186, #133, #128, #149) but is happening again.

Would that mean Twitter has made a change that needs to be accounted for in the script?

Full console log:

```
Refused to execute script from 'https://cdn.syndication.twimg.com/widgets/timelines/**redacted**?&lang=en&callback=__twttrf.callback&suppress_response_codes=true&rnd=0.35221850338987637' because its MIME type ('') is not executable, and strict MIME type checking is enabled.
```

Version of Twitter-Post-Fetcher being used: 18.0.3

**Comment by jasonmayes** [comment]
My guess is something changed then on their side (which is fine as this has always been an unofficial way to do stuff to give devs more time to migrate) but without finding a new way to call we are stuck. Unfortunately I am travelling a lot right now so can not work on this right now, but happy to merge if someone finds a solution that does not break the examples.

**Comment by jasonmayes** [comment]
Wait, mine still works: https://codepen.io/jasonmayes/pen/Ioype are you sure something is not cached?

**Comment by jking-lewis** [comment]
The last example shows the error - https://codepen.io/jking231/pen/OeqPLo

Looks like Twitter has changed something affecting calls to cdn.syndication.twimg.com

**Comment by codepuncher** [comment]
Going to the URL directly in a new browser returns the same error, so clientside caching isn't the issue.

**Comment by jasonmayes** [comment]
Oh I see your code now. Twitter fetcher no longer supports widget IDs you must convert to the new format in the new examples. Widget IDs got deprecated a long time ago once Twitter deleted widgets.
