### ISSUE TITLE
Example 2 is not working when you enable "showImages"

### ISSUE THREAD

**Issue by joyfementira** [jasonmayes/Twitter-Post-Fetcher#204]
On configLikes, it will not show when you enable "showImages".

**Comment by Fermain** [comment]
I am also experiencing this issue. It seems to be related to the regex pattern used to return data-image values.

**Comment by alikuru** [comment]
Same here; setting `showImages` option to `true` seems to break the flow.

**Comment by alikuru** [comment]
FYI, fix offered on #191 worked for me.

**Comment by jasonmayes** [comment]
Merged 191 as everyone said it worked. Thanks for letting me know.
