### ISSUE TITLE
Urls are not properly formatting, it is moving them next to the last line of text in the tweet

### ISSUE THREAD

**Issue by jshaf360kutztown** [jasonmayes/Twitter-Post-Fetcher#206]
Here is an image of the issue:
![OnSiteTweet](https://user-images.githubusercontent.com/25830970/66409765-faa9c980-e9be-11e9-8bb0-7f1f8744887c.PNG) 
Here is the original tweet:
![Tweet](https://user-images.githubusercontent.com/25830970/66409778-00071400-e9bf-11e9-834a-7baed901a0c4.PNG)

**Comment by jasonmayes** [comment]
You will need to add your own breaks using a custom callback. It seems Twitter does not pass formatting in the JSON. This is a styling issue, not an issue with Twitter Fetcher.
