### ISSUE TITLE
No tweets showing

### ISSUE THREAD

**Issue by AttainSG** [jasonmayes/Twitter-Post-Fetcher#207]
Anyone else experiencing this? I couldn't get one of our sites set up with the TwitterFetcher and so decided to check another, again it was no longer working there either, I checked the demo and they don't work there either... yet I can't see there has been an update to the Twitter API? 

Any ideas?

**Comment by aaronunionstudios** [comment]
Yes, I am experiencing this problem as well.

**Comment by SiteSplat** [comment]
No problems at all here. You can see my demo  and I'm using the latest TwitterFetcher version:
https://preview.themeforest.net/item/flatboots-phpbb-32-highperformance-and-creative-modern-forum-for-phpbb/full_screen_preview/8536771?ref=ThemeSplat (scroll to the bottom) - @AttainSG @aaronunionstudios can you check your browser console? Also take a look at the notwork tab in the console. You should see what's going on there.

**Comment by AttainSG** [comment]
Hi @SiteSplat, I don't get any console errors, and it comes back as a 200 in the Network (https://syndication.twitter.com/timeline/profile?callback=__twttrf.callback&dnt=false&screen_name=WetherbyEWI&suppress_response_codes=true&lang=en&rnd=0.4838893918650711) also, on your demo I can't see any of your tweets either? 

Screenshot attached
![tweets](https://user-images.githubusercontent.com/56539748/66758947-33521300-ee97-11e9-864e-2e4b1efa5c84.JPG)

**Comment by SiteSplat** [comment]
Like I said guys, check your console tab and network tab. 
You have something else going on.  I just tested it again for you:
https://twitter.com/SiteSplat

works fine on my end:
![Image of Yaktocat](https://gyazo.com/9b4964144ee29aae97e115d860a11c32.png)



its there on the demo page.

**Comment by AttainSG** [comment]
Hmm, yeah that's strange, like I say it doesn't show on mine, but at the same time I'm not getting any errors in the console, or the network tab. It is working in Microsoft Edge, so... I'll close this down and figure out what's causing it to not work in Chrome. Thanks @SiteSplat
