### ISSUE TITLE
Fetching Tweets

### ISSUE THREAD

**Issue by polarpixel** [jasonmayes/Twitter-Post-Fetcher#208]
Since some weeks or so the script doesn't seem to work anymore.
Has there been a change with the Twitter API?

Thanks!
Peter.

**Comment by SiteSplat** [comment]
working here and still using an older version... Check your browser console log. You might have a JS conflict from some other piece of code. 

Also note, there are some browser plugins will block the twitter script. For example adblocks and specifically plugins  that blocks unwanted scripts. Twitter is part of the unwanted scripts they target. 


see: https://github.com/jasonmayes/Twitter-Post-Fetcher/issues/207
and: https://github.com/jasonmayes/Twitter-Post-Fetcher/issues/202
