### ISSUE TITLE
Emoji is completely missing from tweets

### ISSUE THREAD

**Issue by dvorapa** [jasonmayes/Twitter-Post-Fetcher#211]
Emoji seems to be no longer present in tweet's HTML.

**Comment by jasonmayes** [comment]
Not supported by TwitterFetcher if not passed by Twitter.

**Comment by dvorapa** [comment]
They are passed by Twitter, but TwitterFetcher seems to remove them somehow

**Comment by jasonmayes** [comment]
Can you show me where in the JSON response they are?
