### ISSUE TITLE
Followers number etc

### ISSUE THREAD

**Issue by levipadre** [jasonmayes/Twitter-Post-Fetcher#212]
Hi,

I'm really glad I found your plugin, it's rare but really good. I will definitely donate for you to keep up the good work.

I wanted to ask if it's possible to show follower numbers somehow? Maybe other profile informations? It would be really useful.

**Comment by jasonmayes** [comment]
Unfortunately not using this system you would have to use the regular API.

**Comment by levipadre** [comment]
No problem, cheers.
