### ISSUE TITLE
Hide Replies?

### ISSUE THREAD

**Issue by BN83** [jasonmayes/Twitter-Post-Fetcher#213]
Is it possible to create an option to hide replies? For example, "showReplies: false" ?

**Comment by jasonmayes** [comment]
You are welcome to hide these yourself with css or such. But this would be up to you.

**Comment by BN83** [comment]
@jasonmayes is there not a hide reply option? If it’s only pulling 4 tweets through, hiding replies with css will mean it would only display say 3 of them. Is there now option in the call to twitter to request non replies in the same was as ignoring retweets?

**Comment by jasonmayes** [comment]
Please use the official Twitter API if you want full functionality. This project only has access to the JSON object returned so is not the full API and was only ever designed to be a short term fix for developers who didn't have a backup plan to convert to the OAUTH API many years ago.
