### ISSUE TITLE
In firefox it is not working

### ISSUE THREAD

**Issue by PilarDCV** [jasonmayes/Twitter-Post-Fetcher#215]
Hi,
In firefox it is not working. You can check it using their demo https://codepen.io/jasonmayes/pen/Ioype.
I have tested it on:
- Laptop with Windows (operating system) and Firefox version 75.0 64-bit. Private window (doesn't work) and Normal window (doesn't work).
- Laptop with Linux (operating system) and Firefox version 75.0 64-bit. Private window (doesn't work) and Normal window (if it works).

Do you have any idea what the problem may be?
Thank you!
Regards

**Comment by jasonmayes** [comment]
Working for me, can not replicate. Tried Windows using 75.0, 64 bit. I can only assume its something on your network blocking something.

**Comment by dvorapa** [comment]
It might be blocked directly by Firefox (tracking cookies protection), the protection level can be adjusted in browser settings.
