### ISSUE TITLE
Firefox support

### ISSUE THREAD

**Issue by supagu** [jasonmayes/Twitter-Post-Fetcher#217]
On firefox it looks like the callback function never gets called. It would be really good to be able to determine if there was an error so I can hide the feed. 
Although it would be good if this would work in firefox.

Can someone explain to me how this fetch works so I can do further debugging?

**Comment by jasonmayes** [comment]
It is possible that Twitter has changed something. I am no longer supporting this as folk should have migrated to Twitter's new API by now as its been several years since I made this to help people migrate.
