### ISSUE TITLE
Twitter likes is sorted by date not by recently liked

### ISSUE THREAD

**Issue by dundundunnn** [jasonmayes/Twitter-Post-Fetcher#219]
how do you get this to be sorted by recently liked not sorted by date?
https://syndication.twitter.com/timeline/likes?suppress_response_codes=true&screen_name=ricegnat

**Comment by jasonmayes** [comment]
I have not looked into this in years, this solution was only ever supposed to give people some time to figure out OAUTH before moving to the official API. Essentially you are at the mercy of whatever data you can get back from the JSON response if not using the official API from Twitter. If there is no URL parameter you can specify to do that you would have to write a custom sorting function yourself on the data that comes back
