### ISSUE TITLE
Publish to npm?

### ISSUE THREAD

**Issue by bfred-it** [jasonmayes/Twitter-Post-Fetcher#25]
Now that we have [CommonJS support](https://github.com/jasonmayes/Twitter-Post-Fetcher/pull/23), we could add it to npm as well: https://gist.github.com/coolaj86/1318304

**Comment by jasonmayes** [comment]
SGTM

**Comment by dougmacklin** [comment]
Hey @jasonmayes and @bfred-it thanks for all your hard work on this script. Just wondering, is there a reason it was never published to npm? Sorry if it was, I can't find seem to find it.

**Comment by Wtower** [comment]
+1

**Comment by dougmacklin** [comment]
@Wtower looks like this was implemented: https://www.npmjs.com/package/twitter-fetcher. Thanks @jasonmayes!

**Comment by jasonmayes** [comment]
No problem.
