### ISSUE TITLE
Crosswalk android Build

### ISSUE THREAD

**Issue by Nahuelc** [jasonmayes/Twitter-Post-Fetcher#27]
Hey i`mtrying to use the fetcher to build a webapp but i have a problema. When i export the proyect to android crosswalk (via intel xdk) the twitter fetch doesnt work at all but when i use it in my localhost it works just fine. is this a compatibility issue?

**Comment by jasonmayes** [comment]
I am afraid I have never used crosswalk. The JavaScript code should be compatible with all popular browsers. My guess is that maybe the web interface crosswalk is using does not support some of the functions? I would be surprised if that was the case though as this even works on Internet Explorer! :-) I do know however that if you try and run the script from a non http or https context, it wont work - eg from file:// - this is working as intended as it should not be run via file:// protocol.

**Comment by Nahuelc** [comment]
Hi! thank You!
One last question.. Is there anyway i can modify the code so it run via
file:// protocol?

On Fri, Jan 16, 2015 at 7:03 PM, Jason Mayes <notifications@github.com>
wrote:

> I am afraid I have never used crosswalk. The JavaScript code should be
> compatible with all popular browsers. My guess is that maybe the web
> interface crosswalk is using does not support some of the functions? I
> would be surprised if that was the case though as this even works on
> Internet Explorer! :-) I do know however that if you try and run the script
> from a non http or https context, it wont work - eg from file:// - this is
> working as intended as it should not be run via file:// protocol.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jasonmayes/Twitter-Post-Fetcher/issues/27#issuecomment-70329843>
> .
>



-- 
"El que no detecta los males cuando nacen, no es verdaderamente prudente."
Niccolò Machiavelli

**Comment by jasonmayes** [comment]
I do not believe so. By mixing protocols you force the browser cross-origin security to kick in which bans you from accessing file. Maybe under your browser settings there might be an option to disable this, but I am not sure. It was never designed to be run from file://
