### ISSUE TITLE
Examples not working on my machine. 

### ISSUE THREAD

**Issue by AdamDenoon** [jasonmayes/Twitter-Post-Fetcher#28]
Codepen examples work great.  jasonmeyes.com examples work great. I download the zip, extract all the files/folders to the same directory, open the index.html, and it's not working. It can read all the files in the correct directories, and editing CSS makes effective changes... just can't pull Twitter info.

Furthermore, when I download zip directly from codepen, and extract the zip files/folders to same directory, I open index.html and examples won't populate.

I've tested on both MAC OSX (Yosemite) and Windows 7 Professional (both 64bit), with Firefox, Safari, Chrome, and Internet Explorer. Still nothing.

**Comment by AdamDenoon** [comment]
Furthermore, when I download zip directly from codepen, and extract the zip files/folders to same directory, I open index.html and examples won't populate.

**Comment by AdamDenoon** [comment]
I've tested on both MAC OSX (Yosemite) and Windows 7 Professional (both 64bit). Still nothing.

**Comment by jasonmayes** [comment]
Of course it wont work you are running it via file:// It is trying to get content from a CDN which is on a http connection. This will cause a cross domain issue. You MUST run it from a web server via http or https.
