### ISSUE TITLE
is it possible to show post one by one with carousel ?

### ISSUE THREAD

**Issue by xpeeder** [jasonmayes/Twitter-Post-Fetcher#29]
Hi there its really great and easy way to use plugin :)

i have tried to use with carousel one by one. (i have tried owl carousel )

is it possible ??

Thanks

**Comment by jasonmayes** [comment]
I am afraid I have no idea to what you are referring?  1 by 1 carousel / owl? I have never used these products. In short it can be used with anything if you can get that thing supports content being injected into it.

**Comment by cam3ron2** [comment]
yeah, its possible. I use owl carousel to do just that. Check the footer on http://extenua.com/

**Comment by xpeeder** [comment]
@cam3ron2 wow looks cool :+1:  if you dont mind can you share this code with me :) 

here is my email starxpeed[@]gmail.com 

Thank you

**Comment by jasonmayes** [comment]
Great to see!

**Comment by Joel-Mercier** [comment]
Hey @Ataurr :)
Do you mind sharing the code you used to display one tweet per slide in owlcarousel ? I'm struggling to   figure out how to split the tweets.
Thank you very much and great work @jasonmayes !

**Comment by binarymist** [comment]
+1
