### ISSUE TITLE
User-configurable markup sequence

### ISSUE THREAD

**Issue by baloneysandwiches** [jasonmayes/Twitter-Post-Fetcher#32]
One other thing: I'd like to be able to specify markup order of the various elements. I imagine I'm not the only one. Different ways to do this, but the API could look something like this. 

````
twitterFetcher.fetch( {
  "domId": 'example-with-custom-sequence',
  "maxTweets": 5,
  "enableLinks": true,
  "markupSequence": [
    "time-posted",
    "user",
    "interact"  
  ]
});
````

(I am happy to help if this is something you're interested in. I think there could be some major interest/exposure in this because it's so much easier than the alternative.)

**Comment by jasonmayes** [comment]
That seems cool. If you can make a PR for that I can take a look at code. Please note the browsers we need to support for any new code written :-) Thanks!
