### ISSUE TITLE
Customise html output

### ISSUE THREAD

**Issue by gdharding** [jasonmayes/Twitter-Post-Fetcher#33]
Hi there,

Thanks for this, it's a real time saver.

Is there a way I can customise the HTML output of a tweet? For example access the inner content of p.timePosted independently of the rest of the tweet?

At present trying to parse the string returned with jQuery but it's getting a little messy, plus not working to boot!

Cheers

**Comment by jasonmayes** [comment]
Currently the only way to do this is like the advanced example where it returns to you the tweets which you can then manipulate as required. 

You might be able to make your life easier by simply creating a new variable which is say a DIV eg:

var temp = document.createElement('div');

And then inject the returned HTML:

temp.innerHTML = tweets[n];

You can then use regular jquery functions on temp variable as it is just a HTMLElement which has not yet been added to the DOM - but all the functions etc are there for to you to use eg querySelector / getElementById etc...

**Comment by gdharding** [comment]
Thanks very much! As soon as your site's back online I'll be sure to put a pint behind the bar for you.

**Comment by jasonmayes** [comment]
@gdharding Wow, I did not realise my site was down. Should be back up now! Seems my server got restarted by host. Thanks for letting me know.

**Comment by gdharding** [comment]
No probs!

**Comment by jasonmayes** [comment]
@gdharding  PS Thank you for the beer ;-) Most kind of you.
