### ISSUE TITLE
strip the white space before "twitter verified" tick

### ISSUE THREAD

**Issue by Paul-Browne** [jasonmayes/Twitter-Post-Fetcher#34]
```html
<div class="user">
    <a>
        <img />
        <span>
            <span data-scribe="element:name">Barack Obama</span>
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            <span title="Verified Account" aria-label="Verified Account" data-scribe="element:verified_badge">✔</span>
        </span>
        <span>@BarackObama</span>
    </a>
</div>
```

For some reason twitter injects 8 none breaking spaces before the "twitter verified" tick.
Its possible to remove this gap by adding a negative margin to the verified account span like so...

```css
span[title="Verified Account"] {margin-left: -32px}
```

but it would be nicer to avoid this hack by having the plugin strip the white space, if that's possible. please and thankyou :)

**Comment by jasonmayes** [comment]
Thanks for informing me of this. I dont think it would be too hard to replace &nbsp; For now it is possible by using the advanced example which returns to you each tweet. You could then do a string replace for '&nbsp;' to '' to get rid of it. For example:


var config5 = {
  "id": '345690956013633536',
  "domId": '',
  "maxTweets": 3,
  "enableLinks": true,
  "showUser": true,
  "showTime": true,
  "dateFunction": '',
  "showRetweet": false,
  "customCallback": handleTweets,
  "showInteraction": false
};

function handleTweets(tweets){
    var x = tweets.length;
    var n = 0;
    var element = document.getElementById('example5');
    var html = '<ul>';
    while(n < x) {
      html += '<li>' + tweets[n].replace(/&nbsp;/g, '') + '</li>';
      n++;
    }
    html += '</ul>';
    element.innerHTML = html;
}

twitterFetcher.fetch(config5);
