### ISSUE TITLE
twitter CustomCallbacks

### ISSUE THREAD

**Issue by kcoitk** [jasonmayes/Twitter-Post-Fetcher#42]
Hi, I am new at jQuery. How to pass custom callbacks to make the feed like the attached screenshot?
So that the feed appears like 
First, The Tweets
Second, Twitter Username/Screen-name
Third, Posted Time

https://cloud.githubusercontent.com/assets/5397835/7674977/f71fccbc-fd53-11e4-98e9-e9af6e130a5a.jpg

**Comment by jasonmayes** [comment]
Please see some of the tutorials in the code. It is up to you to do something with the return raw data if you use the custom callback method.
