### ISSUE TITLE
[FR] Auto-refresh

### ISSUE THREAD

**Issue by Fennoman** [jasonmayes/Twitter-Post-Fetcher#43]
A neat feature to have is an inbuilt auto-refresh to refresh the twitter widget every minute or so. As of right now, when I call the function on a timeout it creates a new `script` element in the head of the document every time the function is called.

**Comment by jasonmayes** [comment]
Thanks for submitting. Shall look into this.

**Comment by jasonmayes** [comment]
Now fixed in 13.1 - it will no longer add new script files endlessly. You can now safely use your timeout. I suggest not refreshing more than once a minute though, there is no need for that.
