### ISSUE TITLE
ie8 - Object doesn't support this property or method

### ISSUE THREAD

**Issue by razz3251** [jasonmayes/Twitter-Post-Fetcher#44]
Great work :) Unfortunately I am repeatedly running into error in ie8. I have stripped down the code to the bare min but still getting this issue using v13.0.

**Comment by jasonmayes** [comment]
Can you tell me the property or method it states is not supported? Thanks.

**Comment by razz3251** [comment]
Appreciate the response ;) Removing .fetch() call stops the error occurring.

**Comment by razz3251** [comment]
in non-min script - falis on:

permalinksURL.push(tmp[x].getElementsByClassName('permalink')[0]);

line 206 with

**Comment by jasonmayes** [comment]
Cheers.

**Comment by jasonmayes** [comment]
Now fixed in 13.1

**Comment by razz3251** [comment]
Awesome - will test ;)

**Comment by robe01** [comment]
This may be a silly question but is the latest version (13.1.0) of the Twitter Post fetcher on Bower? I tried doing a bower update to the latest version and it kept giving me 13.0.0, so I manually copied in the files you changed 5 days ago from now. The fix works though, so thank you Jason.
