### ISSUE TITLE
license

### ISSUE THREAD

**Issue by kunzphp** [jasonmayes/Twitter-Post-Fetcher#45]
Hey, nice plugin :)
However could you tell us what license applies for the code?
Thank you so much and have a nice day!

**Comment by jasonmayes** [comment]
I am happy to use as you wish so long as you leave the original comments/disclaimers in the code.

**Comment by kunzphp** [comment]
What about us using it instead of you :) (Typo?) Is it possible to specify a common license like MIT or Apache for the code? Otherwise we would have to code our own plugin, because there is no common sense what usecases are ok and which are not -> commercial use, sell a product with this included etc.

**Comment by jasonmayes** [comment]
Added: https://github.com/jasonmayes/Twitter-Post-Fetcher/blob/master/License.txt

Essentially MIT. Use how you wish. A beer / coffee donation is always appreciated but not required. :-)
