### ISSUE TITLE
Add ability to load additional pages in a timeline

### ISSUE THREAD

**Issue by smilledge** [jasonmayes/Twitter-Post-Fetcher#46]
Would it be possible to add the ability to load the next page of tweets in a timeline.

It looks like the following endpoint ignores the `max_id` parameter;

```
https://cdn.syndication.twimg.com/widgets/timelines/...
```

However, after adding `paged` to the path it returns the correct results (only if a max_id is provided);

```
https://cdn.syndication.twimg.com/widgets/timelines/paged/ ... &max_id=614070890763014146
```

**Comment by jasonmayes** [comment]
Can you provide a full working example for the URLs please? You are saying this allows the user to grab more than last 20?

**Comment by smilledge** [comment]
Looks like this endpoint also only allow you to load up to 20 results, but it would allow loading additional pages of tweets.

**Example URL for loading first 20 tweets:**
https://cdn.syndication.twimg.com/widgets/timelines/616410887595778048?callback=__twttr.callbacks.tl_616410887595778048_1&dnt=false&domain=localhost%3A5000&lang=en&suppress_response_codes=true&t=1595332

**Loading the next page:**
https://syndication.twitter.com/widgets/timelines/paged/616410887595778048?callback=__twttr.callbacks.tlPoll_616410887595778048_1_615511865754525696&dnt=false&domain=localhost%3A5000&lang=en&max_id=615511865754525696&suppress_response_codes=true

**Comment by jasonmayes** [comment]
The 2nd link does not seem reliable to me - currently getting not the data expected.
