### ISSUE TITLE
Unique containers for each tweet

### ISSUE THREAD

**Issue by dkjoseph** [jasonmayes/Twitter-Post-Fetcher#47]
Very much appreciate this script. Makes life much easier.

Im researching the possibility to place tweets in various places on the same page.  Instead of outputing the tweets to one container, I would like to loop through the feed, assign each individual feed to a var, and maybe slice the results (1 item) for each container. 

something like this: 
$("#twitter1").html(items.slice(0, 1));
$("#twitter2").html(items.slice(1, 2));
$("#twitter3").html(items.slice(2, 3));

    <ul>
        <li id="twitter1"></li>
        <li id="other-item"></li>
        <li id="twitter2"></li>
        <li id="random-item"></li>
        <li id="twitter3"></li>
    </ul>

thank you for any tips, advice...

**Comment by jasonmayes** [comment]
You can do this quite easily using the advanced example which passes you an array of tweets with which you can do with as you wish. Please see the comments in the example file js.

**Comment by dkjoseph** [comment]
Thank you! unfortunately, I am getting a console error:  "Uncaught TypeError: Cannot read property 'appendChild' of null"

I believe this is because instafeed is looking for the instafeed container in the DOM, which I don't really need since im appending the items separately.  Any ideas?

thank you!
