### ISSUE TITLE
Link query string often too long

### ISSUE THREAD

**Issue by M-Willett** [jasonmayes/Twitter-Post-Fetcher#52]
At the risk of being too localised, is it possible to have an option to remove query strings? More specifically, analytics-based query strings.
`?utm_medium=feeds&utm_source=data-analytics …` for example.

Or limiting the number of characters? 
Or even just showing the twitter shortened link instead, ie - `t.co/dkj...`

**Comment by jasonmayes** [comment]
Which links are you referring to?

**Comment by M-Willett** [comment]
The alphr link in this example. You're breaking the URI into spans anyway which is useful but something like `maxchar = 30` would be ideal. Otherwise, can't fault this plugin!
![screen shot 2015-09-29 at 10 21 36](https://cloud.githubusercontent.com/assets/2579403/10160199/f33efff6-6693-11e5-8ff4-a7739073dc34.png)

**Comment by brandoc0mmand0** [comment]
Having the same issue here. How can we show the twitter shortened link or limit the number of characters?

**Comment by jasonmayes** [comment]
Can anyone confirm if the shortened links are in the JSON response?

**Comment by OxyDesign** [comment]
Yes I confirm that. In the data.body for each link you have the `href` attr which is a `https://t.co/....` and the content of the <a> is the real link separated in several parts with classes `tco-hidden`, `tco-display` and `tco-ellipsis`.

Basically this classes let you hide the first and last parts of the url by using a `display:none` in CSS on `.tco-hidden`.

The issue come from the fact that your strip function removes all the classes therefore it's not possible to style the different parts of the link.

Solutions are, in my opinion, avoiding removing this specific classes or for instance adding an option in the config to replace the content of the link with the `https://t.co/....` (from the `href`).

Let me know your thoughts about that and if you want me to amend something to fix it.

Thanks

**Comment by jasonmayes** [comment]
Looking at OxyDesign's solution now. :-) Sorry for delay guys, currently in the US so limited access to github whilst on holiday etc.

**Comment by jasonmayes** [comment]
This will be resolved once OxyDesign's patch goes in.
