### ISSUE TITLE
TypeError in console

### ISSUE THREAD

**Issue by ifkas** [jasonmayes/Twitter-Post-Fetcher#53]
Hi, have not changed or modified a single line, just plugged in and have this error in firefox console:

TypeError: f is null
```javascript
...="<ul>";g<a;)h+="<li>"+c[g]+"</li>",g++;f.innerHTML=h+"</ul>"}else A(c);x=!1;0<u...
```

Chrome:
Uncaught TypeError: Cannot set property 'innerHTML' of null

Line 20

**Comment by jasonmayes** [comment]
This probably means the element you are trying to inject the tweets into does not exist. Please ensure your DOM has been created before calling Twitter Fetcher.

**Comment by ifkas** [comment]
Hi Jason, thanks for reply.
Yes, it is right before the body tag, I am building a ghost theme, here is screenshot:

![twitfetcher](https://cloud.githubusercontent.com/assets/987112/10317663/e7136b86-6c65-11e5-8766-a5c034ef9f7d.jpg)

I am using the minified js version of the fetcher.
