### ISSUE TITLE
User Avatar not displaying

### ISSUE THREAD

**Issue by wsb08197** [jasonmayes/Twitter-Post-Fetcher#57]
As of yesterday (16th Novemeber) the user avatar for the twitter feed no longer displays. I was previously using version 12, and updated to the latest version. However, the avatar fails to display on either version

**Comment by FooseTV** [comment]
I've been looking into this as I noticed the icons disappearing in the middle of the day yesterday as well. I traced back to the JSON used to populate the Twitter widgets and I think Twitter changed the HTML format specifically on the user icons. I never looked at this code in detail before but it appears that the <img> element used on the icons no longer has an "src" attribute. Instead there are 2 "data-src" attributes pointing to different sized icons. I'm assuming this is for displaying higher resolution icons on high pixel density displays. I need to dig further but they may be using a new script to display the icon on their actual widget(s) as they still seem to be working.


Here's whats showing up in the TwitterFetch output:

<img alt="" data-src-1x="https://pbs.twimg.com/profile_images/576399716302393345/o6pG9qqE_normal.jpeg" data-src-2x="https://pbs.twimg.com/profile_images/576399716302393345/o6pG9qqE_bigger.jpeg" data-scribe="element:avatar">


Which corresponds to the raw JSON:

\u003Cimg class=\"u-photo avatar\" alt=\"\"\n        data-src-1x=\"https:\/\/pbs.twimg.com\/profile_images\/576399716302393345\/o6pG9qqE_normal.jpeg\" data-src-2x=\"https:\/\/pbs.twimg.com\/profile_images\/576399716302393345\/o6pG9qqE_bigger.jpeg\"\n         data-scribe=\"element:avatar\"\u003E\n


Here's an example of what's on the Twitter widget now:

<img class="u-photo avatar" alt="" data-src-1x="https://pbs.twimg.com/profile_images/576399716302393345/o6pG9qqE_normal.jpeg" data-src-2x="https://pbs.twimg.com/profile_images/576399716302393345/o6pG9qqE_bigger.jpeg" data-scribe="element:avatar" src="https://pbs.twimg.com/profile_images/576399716302393345/o6pG9qqE_normal.jpeg">


I was using a standard  1080p monitor so i believe Twitter's widget detected it as a 1x display and wrote the "src" element via a script. I'm looking now to see what script they are using so I can make a quick fix until TwitterFetch can be updated to account for this.

**Comment by JemBijoux** [comment]
Yeah, I found a similar solution - by swapping the data-src-1x (or 2x) value into the image source by default. It means the image loads like normal with a 1x/2x src (but also that the user never gets the other version either).

**Comment by jasonmayes** [comment]
This is now fixed https://github.com/jasonmayes/Twitter-Post-Fetcher/pull/58
