### ISSUE TITLE
Loading a single tweet by url

### ISSUE THREAD

**Issue by jazibobs** [jasonmayes/Twitter-Post-Fetcher#66]
Hey! 

Firstly let me say thank you so much for building this tool, it's incredible! 

I'm not 100% what I'm asking even counts as an issue but is there a way to use the fetcher to do a dataOnly request for a certain single tweet by url or similar?

**Comment by jasonmayes** [comment]
Unfortunately not, this is simply parsing what is available on Twitter CDN which is a JSON file with the 20 most recent tweets for a given widget.

**Comment by AustinPaquette** [comment]
Would the embed feature for a single tweet be insufficient here?

**Comment by jasonmayes** [comment]
Link to example?

**Comment by AustinPaquette** [comment]
@jasonmayes was that addressed to myself or @jazibobs ?
