### ISSUE TITLE
Moment should not be installed together

### ISSUE THREAD

**Issue by meierdasilva** [jasonmayes/Twitter-Post-Fetcher#68]
Well, there is no reason to install the 'Moment' lib together when using bower. The one who wants to use the alternative that uses Moment, will be able to install it. Better than to force the one who dont needs it, to remove it.

**Comment by jasonmayes** [comment]
Where are we forcing someone to ues it?

**Comment by meierdasilva** [comment]
I mean that the package is downloaded together when you get the twitter-fetcher using bower.

**Comment by jasonmayes** [comment]
I am not sure why? I do not have it as a dep?

**Comment by SpikeShape** [comment]
I had the same problem but I just realized that moment.js was written into my own project's package.json so when I updated twitter-fetcher moment.js was installed as well.

**Comment by meierdasilva** [comment]
@jasonmayes, solved. My error, just forget it.Thanxs the attention!
