### ISSUE TITLE
Test script on twitterFetcher.js causes error

### ISSUE THREAD

**Issue by meierdasilva** [jasonmayes/Twitter-Post-Fetcher#71]
The piece of code below seems to be a test. Lines 370 until 380. 

`var config8 = {
  "id": '345170787868762112',
  "dataOnly": true,
  "customCallback": populateTpl
};

twitterFetcher.fetch(config8);

function populateTpl(tweets){
  console.log(tweets);
}`

I got the error: "Uncaught ReferenceError: twitterFetcher is not defined" on Console.
After removing it the script works again.

**Comment by jasonmayes** [comment]
You would need to include the twitterFetcher script as well to use the example code.  https://github.com/jasonmayes/Twitter-Post-Fetcher/blob/master/js/twitterFetcher_min.js
