### ISSUE TITLE
bower package ist ouf of date

### ISSUE THREAD

**Issue by meierdasilva** [jasonmayes/Twitter-Post-Fetcher#72]
Bower gets the version 14.0.0 instead of the 15.0.0

**Comment by fortybelowzero** [comment]
Bizarrely mine still gets 13.1.0 

(i'm pretty new to bower - am I doing something wrong? i tried:

`bower update twitter-fetcher`
and 
`bower update -f twitter-fetcher`

but get this output:
```
> bower update -f twitter-fetcher
bower twitter-fetcher#~13.1.0  resolve git://github.com/jasonmayes/Twitter-Post-Fetcher.git#~13.1.0
bower twitter-fetcher#~13.1.0 download https://github.com/jasonmayes/Twitter-Post-Fetcher/archive/13.1.0.tar.gz
bower twitter-fetcher#~13.1.0  extract archive.tar.gz
bower twitter-fetcher#~13.1.0     invalid-meta twitter-fetcher is missing "ignore" entry in bower.json
bower twitter-fetcher#~13.1.0         resolved git://github.com/jasonmayes/Twitter-Post-Fetcher.git#13.1.0
bower twitter-fetcher#~13.1.0          install twitter-fetcher#13.1.0
```

**Comment by jasonmayes** [comment]
Ah I think I need to make a new release. Will do that now. Let me know if that fixes it.

**Comment by meierdasilva** [comment]
I dont know why, using bower update i still get the 13.1.0
Cleaning the bower cache didnt solve the problem. My solution to keep it correctly update was uninstall and get it again from bower. The 15.0.0 arrived!

Thanx!

**Comment by jasonmayes** [comment]
:-)
