### ISSUE TITLE
Tweet time is undefined in Firefox as there's no .textContent fallback to .innerHtml

### ISSUE THREAD

**Issue by fortybelowzero** [jasonmayes/Twitter-Post-Fetcher#73]
Hello!

Just noticed a little buggette - the time attribute when requesting dataOnly is undefined in firefox as it doesn't support innerText - looks like you have a test for innerText support and fall-back to .textContent elsewhere in the code but missed it on line 254 (latest v15 build), i've patched my local copy from:

`time: times[n].innerText,`

to: 

`time: times[n].innerText ? times[n].innerText : times[n].textContent,`

Kind Regards,
Rick.

**Comment by jasonmayes** [comment]
Thanks! Good spot. I have updated refs to textContent :-) As this is supported everywhere: http://caniuse.com/#feat=textcontent
