### ISSUE TITLE
Debugging config left in recent commit

### ISSUE THREAD

**Issue by mikehdt** [jasonmayes/Twitter-Post-Fetcher#75]
Hi, thanks for this awesome script :)

It looks like this commit:
https://github.com/jasonmayes/Twitter-Post-Fetcher/commit/ceb1032659362e6d05c9029767506f7f614d9ef9

added some code at the end to do a test config pull, and then console log its output. It's in both the development and minified production versions of the script. Might need to take it back out? :)

**Comment by meierdasilva** [comment]
#71 
It is what i mean here.

**Comment by bz123** [comment]
https://github.com/jasonmayes/Twitter-Post-Fetcher/blob/master/js/twitterFetcher.js#L379

thats been left there, same with the min js

**Comment by mikehdt** [comment]
The question is, why? When you integrate the script with your own code, it will fetch your request _as well as_ this spurious demo request to an unrelated Twitter timeline. As best I can tell, this is testing code which should not be in the core script.

I've cut it out in my own project and it still works just fine. I'm guessing its inclusion is accidental :)

**Comment by jasonmayes** [comment]
Fixed! Sorry, I was debugging, and accidentally committed that. Removed in 15.0.1.

**Comment by bz123** [comment]
thanks @jasonmayes  awesome work
