### ISSUE TITLE
Insecure Reponse Error

### ISSUE THREAD

**Issue by qwertwerty21** [jasonmayes/Twitter-Post-Fetcher#78]
Hey Jason, 

Your Twitter Fetcher is awesome and I've been using it without problems for the  last couple of weeks, but today, when I tried to load it I got this error message from the Console:

twitterFetcher.js:163 GET https://cdn.syndication.twimg.com/widgets/timelines/708033764807483393?&lan…witterFetcher.callback&suppress_response_codes=true&rnd=0.5455620516036825 net::ERR_INSECURE_RESPONSE

I did some researching on my own and some people are saying it's a protective feature from Chrome, which considers this resource insecure and blocks it, but like I said, I've been using your API for the last few weeks without a hitch, so I'm a bit confused as to why the browser suddenly started throwing errors today. What are your thoughts? Do you think it's a problem on my end or no?

**Comment by admilne** [comment]
I've got the same issue, also in Chrome. I'm sure this was working around half an hour ago though so i'm not sure if this is actually an issue with Twitter? Seems like this has stopped working in MS Edge now too.

**Comment by jasonmayes** [comment]
Is this issue still occurring? I cant seem to replicate. If this is a Chrome blocking thing, it is out of my control unfortunately and you would need to submit a request to chrome. I heard somewhere firefox was blocking as it thought this Twitter url was used to track usage - once again this is a Firefox thing, not this script. Sorry I can not do more for this!

**Comment by admilne** [comment]
Not sure what the problem was but it appears to be working now so perhaps there was some temporary glitch with Twitter. Thanks though, love Twitter fetcher!

**Comment by jasonmayes** [comment]
:-)

**Comment by qwertwerty21** [comment]
Yeah, seems like it was a temporary problem. Thanks again!
