### ISSUE TITLE
Return the number of retweets and favourites in dataOnly mode

### ISSUE THREAD

**Issue by jazibobs** [jasonmayes/Twitter-Post-Fetcher#79]
I was just wondering if its possible to retrieve the number of retweets and favourites a certain tweet has using the dataOnly mode.

Is this something which can currently be done?

**Comment by jasonmayes** [comment]
Not currently. If you figure out this feel free to make a pull request. You will need to check the returned JSON response to see if this data is contained inside of it. If it is,you will then need to find a robust way to extract it.
