### ISSUE TITLE
Tweets no longer appearing

### ISSUE THREAD

**Issue by MichaelPereiraUK** [jasonmayes/Twitter-Post-Fetcher#80]
I've had this working for a long while now but as of recently ( not sure when ) it's no longer working.

The AJAX call to Twitter comes back with the following.

```
/**/twitterFetcher.callback({headers: {status: 404, message: "Widget configuration is not found."}});
headers: {status: 404, message: "Widget configuration is not found."}
```
I've double checked the widget still exists and the ID matches, there's no other JS errors on the page and the element exists. It simply adds an empty list.

**Comment by drogers98** [comment]
@MichaelPereiraUK Not sure if it will help, but I just hit the exact same issue, and updating to most recent version fixed my issues.

**Comment by jasonmayes** [comment]
You need to update to latest version. Twitter pushed a change so had to change code to compensate. Thanks.

**Comment by MichaelPereiraUK** [comment]
:thumbsup:
