### ISSUE TITLE
Downloads images when images are disabled and ignores "show user": false

### ISSUE THREAD

**Issue by finnbuster** [jasonmayes/Twitter-Post-Fetcher#81]
I've set up a pen where I am trying to pull in one posts without images.

http://codepen.io/anon/pen/vGagWV?editors=1011

Even so, twitterFetcher.fetch() is pulling in images of not just one post but many posts from the twitter feed which is really slowing downloads down.

![image](https://cloud.githubusercontent.com/assets/2063384/14732528/e7cb513a-089e-11e6-805c-1e5c847df234.png)

How do I stop the function from pulling in images? I just want the data and want to format it with a custom callback function.

**Comment by mattnguyenn** [comment]
that 2.4Mb photo tho

**Comment by finnbuster** [comment]
I don't want any images to download

**Comment by finnbuster** [comment]
`function showTweets(tweets) {
  console.log(tweets)
  var x = tweets.length;
  var n = 0;
  var element = $('.latest-tweet');
  var html;
  while(n < x) {
    // html +=  tweets[n];
    html = "<span class='tweet'>" + tweets[n].tweet + "</span>" + tweets[n].author;
    n++;
  }
  element.html(html);
}

var config8 = {
  "id": '688949189833695232',
  "maxTweets": 1,
  "enableLinks": true,
  "showUser": false,
  "showTime": false,
  "dateFunction": '',
  "showRetweet": false,
  "dataOnly": true,
  "showImages": false,
  "customCallback": showTweets
};

twitterFetcher.fetch(config8);`

**Comment by finnbuster** [comment]
function showTweets(tweets) {
  console.log(tweets)
  var x = tweets.length;
  var n = 0;
  var element = $('.latest-tweet');
  var html;
  while(n < x) {
    // html +=  tweets[n];
    html = "<span class='tweet'>" + tweets[n].tweet + "</span>" + tweets[n].author;
    n++;
  }
  element.html(html);
}

var config8 = {
  "id": '688949189833695232',
  "maxTweets": 1,
  "enableLinks": true,
  "showUser": false,
  "showTime": false,
  "dateFunction": '',
  "showRetweet": false,
  "dataOnly": true,
  "showImages": false,
  "customCallback": showTweets
};

twitterFetcher.fetch(config8);

**Comment by finnbuster** [comment]
I would expect this to not show any images and not render them

**Comment by jasonmayes** [comment]
This has been reported before. It is a browser issue where by when you create elements in memory in JS, without actually adding them to the DOM, the browser tries to be clever and pre fetch the images so they load faster when you do add it to the DOM. In TwitterFetcher's case, only a subset is ever added to the DOM, but the browser does not realise this.
