### ISSUE TITLE
Add follow to tweets interact section

### ISSUE THREAD

**Issue by BryanBarrera** [jasonmayes/Twitter-Post-Fetcher#82]
How could we add a 'follow' button to the 'interact' div? 

As of now the plugin outputs, reply, favorite and retweet. I want to add follow to this section, how could one make this update?

Thanks.

**Comment by jasonmayes** [comment]
You would simply click on the profile and click follow manually. AFAIK there is no one click solution to do this without user accepting otherwise every-time you visit a website you could get people to follow you without warning which is a security issue.

**Comment by BryanBarrera** [comment]
Ok, how about this. How could one add a 'Follow' link or button to the interact div/section?

Thanks for the quick response.

**Comment by jasonmayes** [comment]
See the advanced example in the JS section - here you can write out whatever HTML you wish with each tweet. You could simply grab the Twitter username and make a hyperlink to that page on twitter as a "Follow" button. Then when someone clicks it they are taken to the person's profile, and they can follow the user.
