### ISSUE TITLE
No way to call for smaller images

### ISSUE THREAD

**Issue by ecupaio** [jasonmayes/Twitter-Post-Fetcher#83]
The images that appear in the posts are the :large format and I don't see a method or variable in which I can change that. Though the [timeline widget](https://dev.twitter.com/web/embedded-timelines/parameters) does not appear to have a parameter for that either.

**Comment by jasonmayes** [comment]
Indeed, you could always resize in css, although that obviously does not solve file weight, but if its purely an aesthetic thing, can be CSS fixed.
