### ISSUE TITLE
Where to get Widget ID

### ISSUE THREAD

**Issue by ingfdoaguirre** [jasonmayes/Twitter-Post-Fetcher#84]
Hi, I was trying to get my widget ID, but when I created a new widget twitter takes me to https://publish.twitter.com/# and then I get something like this

<a class="twitter-timeline" href="https://twitter.com/TwitterDev">Tweets by TwitterDev</a> <script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>

If you can see, there is no widget id, so I cant use you plug in :( .

Hope that you can help me.

**Comment by infinitysgame** [comment]
Looks like Twitter have changed the way timelines are embedded. No more Widget IDs.

https://blog.twitter.com/2016/embedding-twitter-timelines-just-got-a-lot-easier

**Comment by ingfdoaguirre** [comment]
Then it converts Twitter-Post-Fetcher to be obsolete?

**Comment by infinitysgame** [comment]
Possibly. Unless there is an alternate method by which to generate a Widget ID. They made changes only yesterday, so I'm not sure.

**Comment by jasonmayes** [comment]
Interestingly TwitterFetcher still works with the old IDs so that means they are hiding them in the URL...

**Comment by ingfdoaguirre** [comment]
But only I can create a search widget ID, is there an option to configure what data appears in the fetcher? for example, i want to show a list with the search widget.

Thank you

**Comment by infinitysgame** [comment]
Yep. Seems existing widget IDs continue to work, but I can't see an option/way to generate new ones (except search).
