### ISSUE TITLE
Regular Twitter widgets no longer kept in admin, thus impossible to get widget ID

### ISSUE THREAD

**Issue by knauso** [jasonmayes/Twitter-Post-Fetcher#85]
Hi,

First I want to say that I was using this awesome script for years, thanks for this!

Twitter now has a new way of creating widgets and they are no longer kept in admin area, you just get the code and it is without any ID (for your own Tweets at least).
So it is impossible getting valid ID (based on your instructions).

You can go to Twitter account and try to create a new widget and you will see.
Old ones are still there and script can run them, but creating new ones has a different way of setting up.

Any workaround for this?

thanks!

**Comment by ingfdoaguirre** [comment]
Hi, I made this issue  #84 and it gOt closed, but this is a big problem because that makes this script obsolete.

You can get a widget ID making a search widget, but you cant get a Widget ID if you want another type of widget, like a list one.

**Comment by scopeak** [comment]
Yup, i've just found out today from a few clients that the method of creating widgets doesn't give the ID now.

**Comment by jasonmayes** [comment]
Sorry on the previous bug opened I tried with search and that still works like it did before, however as you have stated for some of the other like lists, it has a new process now.

**Comment by jasonmayes** [comment]
OK So I have figured out how to do lists but is going to take me some time to rewrite stuff.

**Comment by scopeak** [comment]
Awesome! Look forward to it 👍

**Comment by jasonmayes** [comment]
Done! Check version 16 for list support. I shall have to take a look at the other types later its midnight here. Please make a bug for each other type if you need it and will look into that on a priority basis.

**Comment by scopeak** [comment]
Brilliant! Hoping to see if can get the user type working as using it to show users timeline. Will open a new ticket for it soon.

**Comment by jasonmayes** [comment]
Thanks

**Comment by ingfdoaguirre** [comment]
Hi, is this the new way to fetch lists?

`var configList = {
  "list": {"listSlug": 'inspiration', "screenName": 'jason_mayes'},
  "domId": 'example2',
  "maxTweets": 5,
  "enableLinks": true, 
  "showUser": true,
  "showTime": true,
  "showImages": true,
  "lang": 'en'
};
twitterFetcher.fetch(configList);`

thnk you

**Comment by nmacd85** [comment]
@ingfdoaguirre this looks correct to me as the id "exampleList" isn't in any examples in exampleUsage.js @jasonmayes please confirm, and update? :)

**Comment by knauso** [comment]
@ingfdoaguirre yes I have tested it, that is the proper way and it works, thanks to Jason.
Waiting for the similar fix for Profile widget, I am glad he could adapt his script so fast :)

**Comment by jasonmayes** [comment]
Oh looks like I forgot to update the DOM ID in the example. Will correct that
