### ISSUE TITLE
Fix for new way of creating Twitter widgets without ID - type: Profile

### ISSUE THREAD

**Issue by knauso** [jasonmayes/Twitter-Post-Fetcher#86]
As you wrote in issue [#85](https://github.com/jasonmayes/Twitter-Post-Fetcher/issues/85) I am creating this ticket for the widget I need the most. Thanks for looking into this new widget issue so fast already :)

I just need the possibility to add widget that pulls all feeds from a certain user.
That would be a widget type now named: Profile

(I see they are showing re-tweets as well in the new widget so if there is option not to show it, that would be great)

thanks!

**Comment by scopeak** [comment]
Thanks for opening this, was just about to! 

Cheers 👍

**Comment by jasonmayes** [comment]
Thanks for making the request. I shall see if I can find out how to do that today.

**Comment by jasonmayes** [comment]
This is now fixed. I have added support for profiles and also for profile likes and user lists. 3 new features all of which do not use ID's but instead the new format which you can see in the examples.

**Comment by scopeak** [comment]
Deployed and done. Cheers for the speedy fix @jasonmayes 👍
