### ISSUE TITLE
domId will not work is there is a dash in the name

### ISSUE THREAD

**Issue by Moondrop** [jasonmayes/Twitter-Post-Fetcher#87]
Hello, the twitter widget does not output if there is a `-` (dash) in the `domId`. It does not give any console errors, just nothing is outputted.

For example the following will not work:

```
var configLikes = {
  "profile": {"screenName": 'jason_mayes'},
  "domId": 'example-likes',
  "maxTweets": 3,
  "enableLinks": true,
  "showUser": true,
  "showTime": true,
  "showImages": true,
  "lang": 'en'
};
twitterFetcher.fetch(configLikes);
```

**Comment by jasonmayes** [comment]
Can not replicate. Works for me. Please ensure you are using the latest version.
