### ISSUE TITLE
npm module is outdated 

### ISSUE THREAD

**Issue by Werbelow** [jasonmayes/Twitter-Post-Fetcher#89]
love how easy it was to get this working! Just one thing, the npm module is still on 15.0.2

Thanks so much!

**Comment by ahauser31** [comment]
Yeah, just took me 30 min to realize that the outdated module is the reason for the problems I'm having hahaha. Would be great if you could push the new version to npm @jasonmayes ! Thanks for this awesome module!

**Comment by jasonmayes** [comment]
Fixed
