### ISSUE TITLE
Widget ID Problem

### ISSUE THREAD

**Issue by nicolasjuarezn** [jasonmayes/Twitter-Post-Fetcher#90]
Hi!.
Apparently now when you create a widget always appears a URL embedded without id, only the widget to "search" is the one that can manage and get your id.
I would look for a way to get the tweets creating an API.

**Comment by nmacd85** [comment]
The new version has a way to get other info without an ID

**Comment by jasonmayes** [comment]
This is solved in v 16.0.1. Please see the new example usage file.

Thanks @nmacd85 for the assistance in replying :-)

**Comment by nicolasjuarezn** [comment]
Thanks @jasonmayes  and @nmacd85 !
