### ISSUE TITLE
New widgets have no more widget ID

### ISSUE THREAD

**Issue by lesleyblankendal** [jasonmayes/Twitter-Post-Fetcher#91]
When creating a new widget after the update on twitters end https://blog.twitter.com/2016/embedding-twitter-timelines-just-got-a-lot-easier new widgets no longer produce a widget ID.

Trying to trick it by creating a search widget (which does still produce a widget ID) and entering from:accountname to cheat and create a timeline. This will only surface tweets that fall within the last 7 days.

Are you planning to implement the new twitter changes and remove the twitter widget ID or is there another way to create a new widget in a way that still produces a widget ID that I don't know of?

**Comment by jasonmayes** [comment]
It has already been done. Please read recent closed requests! Use latest version (currently 16.0.1) which supports without IDs now.
