### ISSUE TITLE
can't get widget id from twitter url

### ISSUE THREAD

**Issue by ahmetsali** [jasonmayes/Twitter-Post-Fetcher#92]
Hi, first of all thanks for this great plugin, it seems like twitter has updated their widget creation process, we can no longer get the widget id from url, twitter redirects me to publish.twitter.com when i want to create a widget, and in that page i can see the embed code but still no widget id appears, just username. Can you possible fix this, please?

**Comment by jasonmayes** [comment]
It is already fixed. Please read the github commits and previous bugs.
