### ISSUE TITLE
Impossible to get the twitter widget ID

### ISSUE THREAD

**Issue by romain-granai** [jasonmayes/Twitter-Post-Fetcher#93]
Since few days, "Embedding Twitter timelines just got a lot easier" (https://blog.twitter.com/2016/embedding-twitter-timelines-just-got-a-lot-easier)

The problem now is that you can't save a widget anymore and therefore get the twitter widget ID for the plugin works.

Is there a way to make it works without that widget ID?

Thank you

**Comment by nmacd85** [comment]
var configList = {
  "list": {"listSlug": 'inspiration', "screenName": 'jason_mayes'},
  "domId": 'exampleList',
  "maxTweets": 5,
  "enableLinks": true, 
  "showUser": true,
  "showTime": true,
  "showImages": true,
  "lang": 'en'
};
twitterFetcher.fetch(configList);

This is in the exampleUsage.js. This was updated in the latest version

**Comment by romain-granai** [comment]
Great, thanks a lot, I was still copy/pasting the code on older projects.

**Comment by jasonmayes** [comment]
Indeed please use my latest code which fixes all of this as @nmacd85 mentioned.
