### ISSUE TITLE
Not showing re-tweet

### ISSUE THREAD

**Issue by romain-granai** [jasonmayes/Twitter-Post-Fetcher#94]
Is there a way to display the re-tweet. I'm using this configuration : 

`var configProfile = {
  "profile": {"screenName": 'something'},
  "domId": 'twitter-fetch',
  "maxTweets": 1,
  "enableLinks": true, 
  "showUser": false,
  "showTime": false,
  "showImages": false,
  "showRetweet": false,
  "showInteraction": false,
  "lang": 'en'
};`

but it shows only the tweets from that "profile" but not the re-tweet.

**Comment by jasonmayes** [comment]
You have showRetweet as false. That would need to be set to true.
