### ISSUE TITLE
ideas to prevent: image requests and downloads, empty tweets, and undefined image source

### ISSUE THREAD

**Issue by MrKarlDilkington** [jasonmayes/Twitter-Post-Fetcher#95]
@jasonmayes 

First, thank you again for a very useful program. 

I wanted to run a few code ideas by you and others.
These ideas address:
- when showImages is false and printUser is false, image requests and downloads are made (I looked through closed issues to read your ideas and suggestions on the topic)
- when showImages is false, empty tweets without text are displayed
- new media card types display as having undefined image source
https://github.com/jasonmayes/Twitter-Post-Fetcher/issues/74

Here is a gist with the code changes. Changes made to the original file are wrapped in the comments "CHANGES" and "END CHANGES".
https://gist.github.com/MrKarlDilkington/1d4c1d3bb54638b91b6ac1da230f3c1e

With the changes, if you don't show tweet images or user images, only 1 small request/download is made for the Twitter JSON. The request and download savings is substantial.

**Comment by jasonmayes** [comment]
Thanks for the kind words. This seems great @MrKarlDilkington! Would you be able to submit a pull request? I can add a few comments on that in more detail and hopefully then merge with master. Thank you for sharing this and contributing to TwitterFetcher!

**Comment by jasonmayes** [comment]
This should be now fixed thanks to Karl
