### ISSUE TITLE
Can't create "user timeline" widget

### ISSUE THREAD

**Issue by cdarlens** [jasonmayes/Twitter-Post-Fetcher#97]
I want to show on my website my the two lastest tweets

These are steps:
- Go to www.twitter.com and sign in as normal, go to your settings page.
- Go to "Widgets" on the left hand side.
**- Create a new widget for what you need eg "user time line" or "search" etc.**
- Now go back to settings page, and then go back to widgets page and you should see the widget you just created. Click edit.
- Look at the URL in your web browser, you will see a long number like this: “727179718227836928”
- Use this as your ID below instead!

As you can see in the image attached. **I don't have the option to create a "user timeline widget".  I can only create one for search.**

![twitterfetcherissue](https://cloud.githubusercontent.com/assets/16642768/17040736/92d0aa1e-4f6f-11e6-9212-14971a34eabb.png)

**Comment by oknate** [comment]
It seems twitter updated it's widgets so they don't take IDs.

**Comment by regmtait** [comment]
Hi @oknate @jasonmayes updated the plugin so that it can works without user ids – see the last queries in the example.

**Comment by reinos** [comment]
@regmtait where do you see the example?

**Comment by nmacd85** [comment]
@reinos https://github.com/jasonmayes/Twitter-Post-Fetcher/blob/master/js/exampleUsage.js

**Comment by nmacd85** [comment]
@jasonmayes If you like, I updated the exampleUsage comments to reflect the new Twitter changes. Would you like me to submit a PR?

**Comment by jasonmayes** [comment]
@nmacd85 Thank you but I already added example code in there. I have a todo to move it to the top though as people are not finding it. I shall do that now.
