### ISSUE TITLE
Not seeing option to only pull from your own feed. 

### ISSUE THREAD

**Issue by dancrowe** [jasonmayes/Twitter-Post-Fetcher#98]
Hi, just started using this plugin and I can't seem to find the option to only pull from my feed. Right now if someone tweets @ me it will show up in your app and im trying to avoid this.

**Comment by jasonmayes** [comment]
What config are you using?

**Comment by dancrowe** [comment]
I have been trying to use the below but when I use this nothing show up.

var configProfile = {
  "profile": {"screenName": 'PS_Strategies'},
  "domId": 'pss-feed',
  "maxTweets": 1,
  "enableLinks": true, 
  "showUser": true,
  "showTime": true,
  "showImages": false,
  "lang": 'en',
  "showRetweet": false
};
twitterFetcher.fetch(configProfile);

If i replace the "profile" with a "id" it pulls in the feed but it pulls in everything. Including when people tweet @ me.

var configProfile = {
  "id": '747538539307372544',
  "domId": 'pss-feed',
  "maxTweets": 1,
  "enableLinks": true, 
  "showUser": true,
  "showTime": true,
  "showImages": false,
  "lang": 'en',
  "showRetweet": false
};
twitterFetcher.fetch(configProfile);

**Comment by jasonmayes** [comment]
So for the widget ID version you have to configure via the widget which is no longer supported by Twitter I believe.

As for using the new version can you link me to a live demo so I can see what the error is for nothing showing up?

Cheers

**Comment by dancrowe** [comment]
Sure thing, Here is a link to the live site. 

http://parkstreetstrategies.com/

Yea, I tried to create a twitter widget but they can no longer be saved, they just want you to use the code they give you. My settings now look like this.

`var configProfile = {
  "profile": {"screenName": 'PS_Strategies'},
  "domId": 'pss-feed',
  "maxTweets": 1,
  "enableLinks": true, 
  "showUser": true,
  "showTime": true,
  "showImages": false,
  "lang": 'en',
  "showRetweet": false
};
twitterFetcher.fetch(configProfile);`

Please let me know if you need anymore info.

Thanks for the help

**Comment by nmacd85** [comment]
You're using v15, you need to update to the most recent build to have the config you're using work.

**Comment by DaveFerBear** [comment]
@dancrowe @jasonmayes Was this issue ever solved?  I have the exact same issue - I want to show only MY feed.

**Comment by DaveFerBear** [comment]
Found a solution - in the search query, simply use `from:myusername`
<img width="331" alt="screen shot 2016-09-22 at 3 21 48 pm" src="https://cloud.githubusercontent.com/assets/12205022/18762781/51865190-80d8-11e6-8a1b-c91f252a99e8.png">

**Comment by jasonmayes** [comment]
Are you using the latest version @DaveFerBear or widget ids from the old config?
